### ISSUE TITLE
Fix flame to use pub accepted stuff

### ISSUE THREAD

**Issue by luanpotter** [flame-engine/flame#102]
Pub pandas/analyzer is not capable of using our version of flutter/dart etc.
We need to urgently fix all these problems: https://pub.dev/packages/flame#-analysis-tab-

**Comment by renancaraujo** [comment]
Facing same problem on photo_view. The analyzer uses the stable channel version to analyze packages. What you can do: release "master" versions when you need to fix breaking changes on Flutter's most recent versions (master and dev). Something like `0.11.2-master` 
Versions like that are not rated by pub. 

In this way, flame becomes "stable compatible": The main releases must be compatible with stable channel. 

I'm planning to do something like this but only in the next versions (since one cannot delete versions on Pub 😭)

**Comment by jonasfj** [comment]
Yeah, pre-releases like `-master` or `-dev` is a great way to release stuff that depends on non-stable Flutter or Dart.. It won't hurt your score and you won't drop in search results.

Side note: git dependencies is also going away.

> I'm planning to do something like this but only in the next versions (since one cannot delete versions on Pub)

You can, if you file a deletion request (manually), but right now we don't have tooling to delete latest version... But more importantly, it's always better to just publish a new version and move forward. 
People might depend on a package or version you've published, breaking them wouldn't be nice :)

**Comment by luanpotter** [comment]
We have downgraded in 0.13 to use flutter stable. All changes were made to support that on #106. Thanks a lot @erickzanardo and @jonasfj for taking look into this. Our score is back up again! \o/
