### ISSUE TITLE
Support `shouldRepaint` method

### ISSUE THREAD

**Issue by truongsinh** [flame-engine/flame#110]
In my game, sometimes there is no pixel change at all, it's kind of waste to repaint if I know Skia should not.

**Comment by erickzanardo** [comment]
I am not sure about this, in a Game it is very unusual not needing to re draw something, that is why game usually uses active rendering instead os passive rendering, like normal/simpler applications do.

Also, I think this would change basically nothing on perfomance, since Flutter always strives for, and achieves 60fps on apps, we would only add unnecessary complexity with this method.

That said, are you having any perfomance issues @truongsinh ?

And @luanpotter what are your thoughts on this?

**Comment by truongsinh** [comment]
Just to clarify, the performance is great for my game (just a simple clone of Flappy Bird), even on a crappy Samsung A3 2014.

That being said, when I turn on performance overlay, I see it's always repainting (as you describee as active rendering). I wonder whether having `shouldRepaint` could even further improve performance for some complicated games with hundreds of sprites (both rendering and battery consumption)

**Comment by erickzanardo** [comment]
@truongsinh I am still not sure about this, nevertheless, I created a branch named `should-repaint` which adds a method `shouldRepaint` on the Game class, that you can override and controls its, its default implementation always returns true.

Would you mind making a test and see how this improves the perfomance, battery consumption? To make sure that this is worth the small added complexity?

**Comment by truongsinh** [comment]
Hi, I just tried the `shouldRepaint` method, but the performance overlay is still running (the expectation is that the green indicator not moving anymore when `shouldRepaint` is false).

<img width="400" alt="Screen Shot 2019-06-26 at 6 36 03 PM" src="https://user-images.githubusercontent.com/358585/60176725-59e53300-9841-11e9-8a23-130f38ad0732.png">

**Comment by erickzanardo** [comment]
hm, weird, I have added another commit to the branch. if there any other repaints now, it should be because of stuff of flutter, Flame should not paint anything when the method returns false now. Can't you give your test another try?

**Comment by ProgrammingLife** [comment]
I also do not need to repaint every frame. There are many small games that don't need it. Such as: Sudoku, simple games for kids, educational tests, puzzles/jigsaw (this should be repainted only when we dragging some piece and the rest of the time player just thinks what to do next) and other educational stuff. We don't need aggressive repainting. It would be cool to stop it from repainting when we don't need it.

**Comment by erickzanardo** [comment]
Hey @truongsinh have you had any chance to test this?

**Comment by truongsinh** [comment]
Hi sorry for the late reply, it's still the same, you can check it out at https://github.com/truongsinh/fluttery_dash/tree/should-repaint

**Comment by ProgrammingLife** [comment]
Has it already fixed?

**Comment by erickzanardo** [comment]
So, I did some progress on this, but this is more complicated than I expected.

**Comment by ProgrammingLife** [comment]
@erickzanardo it will be the great feature I'm pretty sure! :)

**Comment by ProgrammingLife** [comment]
So what about this issue? Is this fixed?

**Comment by luanpotter** [comment]
@ProgrammingLife performance when there are no changes in the screen is the same as when there are changes, which is already very good.

It could possibly be improved even more for that case, but it's an edge case for a game to have no change/animation/motion whatsoever. If @erickzanardo is busy and you'd like to take a look at it, I'd be glad to review and then merge your PR :)

You could create a bool method or getter for a Game to override inform the engine that it doesn't need to run render/update. However your game would need to have a way to set that back outside of the update loop so that your game can eventually run it again. I think the solution is to not schedule the for the next tick whatsoever, but when the method is called again, start scheduling again. That will not trigger the render nor the update, and so fps will surely be on the 60 cap. But again, good documentation is key to let the Game override know that it needs to have a way to set his flag back so that the game eventually runs again. Or it would be stuck there forever.

**Comment by ProgrammingLife** [comment]
@luanpotter 
Well, it has a sense. Is Flame possible to update only the whole screen doesn't matter even when just one little object has changed or it can update just one little piece of the screen where the changes happened? As I believe should Skia do :)

**Comment by luanpotter** [comment]
@ProgrammingLife we always update the whole thing. If an object moves, you'd need to repaint where it was with calculating what should be behind it (maybe a complex mix of other objects) plus update where it is now with itself. If you have things like transparency, it gets even trickier. I think doing these kinds of computations is way more expensive than just repainting the whole thing and leaving to the GPU to optimize how to actually change the pixels in the hardware.

**Comment by ProgrammingLife** [comment]
@luanpotter but what if we have just a little changing piece of the screen such as a small particles effect area at the right bottom of the screen where we don't need to update the whole screen. Might be it would be better to set engine to special mode where it finds and updates only the changing areas?

**Comment by erickzanardo** [comment]
@ProgrammingLife I don't think updating only a part of the screen would be better, specially on the example you used, a particle system, even on a small area, makes changes a lot, both on pixel positions, colors, opacity and etc. The algorithm to detect the area that changed, and what changed, would not be very easy to implement, would be error prone and I have serious doubts if that would bring perfomance improvements.

Also, I can't think of a way to detect changes between the frames without a cache frame having been fully draw, and if the frame was already draw, it is just simpler to just drop the last frame entirely and render the new one.

Games are not like other apps, which has small changes according to user input, and on those apps, partial update makes a lot of sense there, on a Game, I don't think it would be effective.

But about the original purpose, I do think we could still make it, "pausing" the engine can be a very good way to pause the game and save battery life, I could see it been used, for example on a game where the inventory menu is made all with Flutter widgets, and it covers the game widget, on that case, the engine could be paused and be resumed after the player exists the menu.

**Comment by ProgrammingLife** [comment]
What about **shouldRepaint** for now? Is this supported well to stop from repainting screen when it's not needed?

**Comment by ProgrammingLife** [comment]
That would be useful to use some components from Flame in Flutter such as NineTile png for creating beautiful modal windows, dialogs. Then we don't need repaint it every frame.

**Comment by erickzanardo** [comment]
@ProgrammingLife we haven't worked on this yet, we have been focusing on other features at the moment.

**Comment by ProgrammingLife** [comment]
@erickzanardo is that feature on your plans? Is it too hard to implement?

**Comment by erickzanardo** [comment]
Fixed on #272 and released on Flame 0.19.1
