### ISSUE TITLE
Scrollable Screen

### ISSUE THREAD

**Issue by brendonanderson** [flame-engine/flame#111]
Is it possible to make it so that my screen is twice as high (in portrait mode) or twice as wide (in landscape mode) and use gestures to scroll to the far right to see what might be happening there, and scroll back to the far left to see what is going on there (or scroll to the top and scroll to the bottom)?

**Comment by erickzanardo** [comment]
You should be able to achieve that by just rendering the screen the size you want, even if it is out of the screen, and using gestures you can use the translate method from canvas to "move the camera" and create the scroll effect you refer to.

Since this is not an issue with flame, I am closing this, but feel free to ask more questions on this thread, or join our discord to get help.
