### ISSUE TITLE
Rive bone animation

### ISSUE THREAD

**Issue by BlockRen** [flame-engine/flame#1112]
# Problem to solve

# Proposal

# More information

**Comment by spydon** [comment]
@renancaraujo do you understand what this means? Is there some special feature of Rive?

**Comment by nmarafo** [comment]
From my point of view there is no need to perform any task in this sense (bones?) Since the animations are controlled from the Rive platform through the creation of animations or 'StateMachine' and in the example of the flame_rive package it is use StateMachine by adding a controller (StateMachineController). I therefore propose to close this issue.
