### ISSUE TITLE
[Tiled] tiles in different layers are conflict each other

### ISSUE THREAD

**Issue by Hwan-seok** [flame-engine/flame#1264]
You can clone my reproduction repo and try it

# Current bug behaviour
tiles in tileset are conflicting with other tiles in other tileset
For example, I have Bending machine tile(furniture tileset) and wall tile(walls tileset) or floor tile(floors tileset) in background layer behind the former.
But the bending machine tile does not rendered.
In my case, I found following rules
1. floors tileset with furnitures or exterior tileset are renders only floor tile
2. floors with interior tileset works OK
3. walls tileset works with nothing
![Screenshot_20211222-160229](https://user-images.githubusercontent.com/38072762/147050287-539b6055-48ef-4769-befb-3030546affeb.jpg)

# Expected behaviour
Renders map as same as the official map editor
![스크린샷 2021-12-22 오후 4 02 18](https://user-images.githubusercontent.com/38072762/147049705-af499e9b-3ae7-4d8c-8256-fc7fcac2cf79.png)

# Steps to reproduce
Compare between Tiled(Official map editor) program and rendered by flame_tiled

- flame_tiled
1. Clone [reproducible repo](https://github.com/Hwan-seok/flutter-flame-tiled-iss-repro) -> Resources in repo are only for reproduction and must not use it for other purposes.
2. flutter pub get
3. flutter run

- Tiled
1. Find tmx map file from cloned repo - `assets/tiles/map.tmx`
2. Open it with Tiled map editor

# Flutter doctor output
``` flutter doctor -v                                           ✔
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.6 20G165 darwin-x64, locale
    ko-KR)
    • Flutter version 2.8.0 at /Users/lafity111/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (13 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/lafity111/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (1 available)
    • SM G977N (mobile) • R3CM6093EAL • android-arm64  • Android 11 (API 30)

• No issues found!
```

# More environment information
* Flame version: 1.0.0

# Log information

```
No abnormal logs
```

# More information

**Comment by spydon** [comment]
Is it rendering the tiles that aren't visible behind other tiles, or do they simply not get rendered at all?

**Comment by Hwan-seok** [comment]
How can I differentiate between them?
I used Layers.
If flame_tiled respected layer order as rendering priority, the latter one is correct.
I think it is simply not get rendered because my layer tree is structured as follows 

```
Background(floors and walls)  --- priority low
\
... 
\
furniture                                   --- priority high
\
...

```
"SOME" furniture does render with floors
![image](https://user-images.githubusercontent.com/38072762/147264980-4ac51c6d-7886-4712-a378-0662346140fe.png)
but "SOME" of rest is not rendered with walls
![image](https://user-images.githubusercontent.com/38072762/147265028-7f455972-cd9e-4a98-af2f-03f398babd56.png)

**Comment by lfraker** [comment]
@spydon & @Hwan-seok I just ran into what I believe is a similar issue, and have a working theory on what's causing it. For me it is occurring when I have layers pulling from different tilesets (and thus different sprite images). Regardless of layer order, some tiles from a spritesheet always overwrite tiles from another spritesheet.

While testing out different fixes, I noticed that the tiles to be rendered are batched in order of their spritesheet images, and then each batch is rendered (see _renderLayer at line 99 and render at line 127 in https://github.com/flame-engine/flame/blob/5c47d7f6d7ed4705a3f19e9119364d9c6e6cff55/packages/flame_tiled/lib/src/renderable_tile_map.dart#L99 https://github.com/flame-engine/flame/blob/5c47d7f6d7ed4705a3f19e9119364d9c6e6cff55/packages/flame_tiled/lib/src/renderable_tile_map.dart#L127).

![image](https://user-images.githubusercontent.com/5459537/149417751-eaf96136-6cbb-43c4-8bff-28e96ff21828.png)

It seems that the batches map is populated by iterating through the tilesets in the map, in order (https://github.com/flame-engine/tiled.dart/blob/cb08bc937f82a6ed42cb47fa9b526446ea8e9f76/lib/src/tiled_map.dart#L167 line 167). Since the map is then iterated and the tileset is rendered in order of the map, when a spritesheet/tileset appears later in the iteration with tiles that conflict (even if it is in a lower layer), the tiles are overwritten.

The manual fix was to change the order that the tilesets appeared in my .tmx file. Unfortunately physically copy/pasting to re-order them ran into a separate issue (I didn't root cause, but it seems like somewhere there is a dependency on the ordering of the tileset elements - this seems suspicious). To alter the order, I had to re-add the tileset and re-tile the layer (this appended the later tileset on at the end of the xml list and fixed the layered rendering for me.

@spydon, the manual fix is tedious and likely will not resolve all cases. Would it be possible to change the batches key to be a 'compound key' of layer/tilemap, then effectively render in layer order (then arbitrary image order within each layer, since there is no possible conflict within a layer)?

**Comment by spydon** [comment]
> @spydon, the manual fix is tedious and likely will not resolve all cases. Would it be possible to change the batches key to be a 'compound key' of layer/tilemap, then effectively render in layer order (then arbitrary image order within each layer, since there is no possible conflict within a layer)?

> Update: If the problem theory and proposed fix seem reasonable and you're not able to get a fix out soon, I'd be happy to submit a PR :). Getting this fix in will make my work much less tedious. Please let me know.

Seems reasonable, and we'd happily review your PR. :)

**Comment by spydon** [comment]
`flame_tiled` version 1.1.0 is now released, thanks to the fix from @lfraker :tada:
