### ISSUE TITLE
Facilitate casting on flame_forge2d's PositionBodyComponent

### ISSUE THREAD

**Issue by erickzanardo** [flame-engine/flame#1382]
# Problem to solve
Currently `PositionBodyComponent` can hold a `PositionComponent`, which allows us to add a `SpriteAnimationComponent` to it for example.

But if we want to manipulate that component, we need to manually cast it like

```dart
(body.positionComponent as SpriteAnimationComponent).playing = false;
```
This leads to both cumbersome and unsafe code.

# Proposal
We should provide a type safe method of retrieving the stored component on the body.

One suggestion (credits to @spydon for the idea) is to add a second generic type on that body to be used on the `positionComponent` attribute.

**Comment by st-pasha** [comment]
And then another question is why is it adding `positionComponent` to the root of the game?

**Comment by spydon** [comment]
> And then another question is why is it adding `positionComponent` to the root of the game?

There is a looot of refactoring needed for flame_forge2d, but it is due to the different coordinate systems. If you have a good idea of how to accomodate this it would be a very good PR, because the current PositionBodyComponent is very dirty.

**Comment by erickzanardo** [comment]
> Ideally this should be handled by the camera, isn't it? The world may live in whatever coordinates it finds the most suitable, and the camera handles converting those coordinates into screen pixels.
> 
> 
> 
> Do you know why this isn't handled via the camera now, were there any challenges with this approach?

Maybe this should be discussed on a different issue since this out of the scope of this one, wdyt?

**Comment by st-pasha** [comment]
With regards to this particular issue, it appears that the proposed solution to introduce a new template parameter will be a breaking change. And then the question is whether it's advisable to make such breaking changes for largely cosmetic benefits. After all, one could always write their own getter
```dart
SpriteAnimationComponent get child => (positionComponent! as SpriteAnimationComponent);
```

Also it would probably make sense to make `positionComponent` final, because right now it can be reassigned at runtime freely.

**Comment by spydon** [comment]
> > Ideally this should be handled by the camera, isn't it? The world may live in whatever coordinates it finds the most suitable, and the camera handles converting those coordinates into screen pixels.
> > Do you know why this isn't handled via the camera now, were there any challenges with this approach?
> 
> Maybe this should be discussed on a different issue since this out of the scope of this one, wdyt?

Created #1384 for it. They are related, because if we do that one first then this issue isn't needed anymore.
It will be quite some work and I won't have time to do it anytime soon, meanwhile this issue would be very quick to fix (if we'd want to do it).
So the question is if anyone is willing to take on #1384.
