### ISSUE TITLE
Adding hasMount future to Component

### ISSUE THREAD

**Issue by erickzanardo** [flame-engine/flame#1417]
# Problem to solve

Right now, Flame components have an attribute to know is that component is already mounted, but there is no way for someone to await for its mount to happen.

# Proposal

This could be simply solved by added a completer on the component base class, expose its future and complete it once it has finished mounted.

# More information

**Comment by spydon** [comment]
Should there be completers for all lifecycle events maybe?
The name should probably be `hasMounted`?
Other than that I think it sounds good. 🙂

**Comment by alestiago** [comment]
@spydon, sounds superb! 

@erickzanardo and I did a POC to see if this was feasible. And turns out we used the same name "hasMounted".

So definitely agree! 🚀

**Comment by spydon** [comment]
> @spydon, sounds superb!
> 
> @erickzanardo and I did a POC to see if this was feasible. And turns out we used the same name "hasMounted".
> 
> So definitely agree! 🚀

Nice! Did you also try for other lifecycle events?

**Comment by st-pasha** [comment]
We need to be careful not to add any unnecessary data members into the core `Component` class though.

**Comment by spydon** [comment]
> We need to be careful not to add any unnecessary data members into the core `Component` class though.

True! Maybe this could be added with a mixin?

**Comment by erickzanardo** [comment]
I am going to start with the hasMounted which is something that already has use for, if we identify more lifecycle that would benefit from it, we can do follow ups.

**Comment by st-pasha** [comment]
what if we modify component's `.add()` so that it returns a future that returns once the component is mounted, instead of only loaded?

**Comment by erickzanardo** [comment]
> what if we modify component's `.add()` so that it returns a future that returns once the component is mounted, instead of only loaded?

That would be confusing IMO, adding and mounting the component are different part of the lifecycle.

**Comment by st-pasha** [comment]
> That would be confusing IMO, adding and mounting the component are different part of the lifecycle.

You probably meant loading and mounting, because adding is not part of a lifecycle -- it's just a method that schedules lifecycle events of loading and mounting. And if the component is already loaded, then it's just mounting.

Of course, right now `.add()` returns the future from the loading part, and changing that to the mounting future may have bad consequences since mounting happens after a considerable delay (or sometimes never). Still, there could be a room for an optional flag to `.add()` so that it would return the mounting future instead. So that the user may write
```dart
await component.addToParent(game, waitToMount: true);
```

**Comment by alestiago** [comment]
I'm somewhat against the flag for the `add`. 

It adds extra complexity for the function and see this as anti-pattern. I think this was raised by Uncle Bob (not sure though have to double check). Personally, a function is a function and should only do a function. This flag makes it do two functions. And additional flags will keep adding functionality to a single function.

What if I want to list to both, when the component is loaded and mounted? 

If we plan to add more lifecycle methods listeners then we will have a bunch of flags and complexity to the `add` method.

I think this `hasMounted` property should be available in all `BodyComponent` in flame_forge2d. I think there is interest on including it with `Component` all together.

I understand the desire to keep the `Component` class simple enough. If there is a strong feeling for this, I think the suggestion @spydon raised regarding the mixin sounds like a good idea. I wonder what name this should have `LifecycleListener`?

I also wonder if this kind of complexity could be somewhat managed by the recently added `LifecyleManager`. I haven't explored this class in depth but just wanted to drop it as a possible suggestion.

Hope my two cents help here.

**Comment by spydon** [comment]
> I understand the desire to keep the `Component` class simple enough. If there is a strong feeling for this, I think the suggestion @spydon raised regarding the mixin sounds like a good idea. I wonder what name this should have `LifecycleListener`?

It's more about performance than keeping it simple, so if the field is look lazily initialized it should be fine.

> I think this `hasMounted` property should be available in all `BodyComponent` in flame_forge2d by default. So I think there is interest on including it with `Component` all together by default to. Hence, if we go down the mixin road, for consistency, I believe this should be already added to the `Component` class.

Why specifically the `BodyComponent`?

> I also wonder if this kind of complexity could be somewhat managed by the recently added `LifecyleManager`. I haven't explored this class in depth but just wanted to drop it as a possible suggestion.

That's a good idea, maybe the completer could live lazily initialized in there.

**Comment by alestiago** [comment]
@spydon , I understand the performance issue and I think it's a key consideration. As you've said a game might have many `Component`s and having this field be eagerly loaded instead of lazy-loaded can impact performance considerably. I fully agree! Great point @spydon ! 🚀

I brought up `BodyComponent` since it's the one I've been messing around with. I've found out sometimes you might require listening when a given `BodyComponent` lifecycle event occurs to adjust properties like limits in joints with which these components are physically bonded. I don't know if these lifecycle events can be practically useful outside `flame_forge2d` world. I would love to see some examples where this new functionality can be used in a real non-forge2d game 😄

**Comment by spydon** [comment]
Closing this since `mounted` and `loaded` was added.
