### ISSUE TITLE
Group logic related to lifecycle of components on the _LifecycleManager

### ISSUE THREAD

**Issue by erickzanardo** [flame-engine/flame#1426]
# What could be improved

Right now, some life cycle related logic lives directly on the Component class, like its state, if it is mounted, its completers and so on.

It would make better maintainable code if this logic would be center on the `_LifecycleManager` and the component would just expose those methods through getters.

# Why should this be improved
Easier to maintain code.

# Any risks?
None come to mind, this is all internal stuff, and we have a good amount of tests ensuring the correct behaviour so a refactor should be safe.

# More information

**Comment by st-pasha** [comment]
The primary difference between `Component` and `_LifecycleManager` is that the latter keeps the transient state only. Meaning, the state that needs to be kept around only for a limited duration of time while the component undergoes certain changes. A good test for whether a property belongs to `_LifecycleManager` is whether the component will continue to function when the `_lifecycleManager` is set to null.

Thus, for example `.parent` and `.children` are permanent properties of `Component`. Likewise `.state`, which is a simple enum, also ought to be in the `Component`, since the component always have some kind of state, whether it's more transient like `loading` or permanent like `mounted`.

The `.isMounted`/`.isLoaded` getters already work via the `state` getter, so don't need to be moved.

The `.nextParent` property is already moved in #1385.
