### ISSUE TITLE
ParticleComponent should be a PositionComponent

### ISSUE THREAD

**Issue by erickzanardo** [flame-engine/flame#1488]
# What could be improved
ParticleComponent if a plan Component, which makes it hard to position when there are camera transformations on the game.

# Why should this be improved
So particle components could easily used alongside the camera system

# Any risks?
This will kind of a minor breaking change.

# More information

**Comment by spydon** [comment]
A risk that I see is that the `PositionComponent` might be a bit heavier component than the `ParticleComponent`, on the other hand `PositionComponent` has gained a lot of optimizations lately. It would be interesting to see if it would make a difference spawning a large amount of  `PositionComponent`s compared to `ParticleComponent`s. If it doesn't make a difference, I think this sounds like a great idea!

**Comment by erickzanardo** [comment]
Cool, I am gonna work on this soon then!

**Comment by st-pasha** [comment]
@spydon `ParticleComponent` is a wrapper around `Particle` (which is not a component), so a single `ParticleComponent` may hold hundreds if not thousands of smaller particles inside. Which means there is little performance loss in making `ParticleComponent` slightly heavier, since this weight will be applied only once to the whole particle system.

Perhaps the name `ParticleComponent` is a bit confusing? Because it seems like there could be one component for every particle, but that's not the case.

**Comment by spydon** [comment]
Right had completely forgotten it was like that, it was a looong time since I looked at the particle system, and I think there barely has been any changes to it for almost two years. Maybe just `ParticlesComponent` then? Feels like most names describing what it does would become very long.

**Comment by st-pasha** [comment]
hmm, how about `ParticleSystem`?

**Comment by erickzanardo** [comment]
I like ParticlesComponent, but it will be a big breaking change instead of a small one, will that be ok?

**Comment by st-pasha** [comment]
We could make a rename, and leave the old name as a deprecated typedef. That way it won't be a breaking change.

**Comment by erickzanardo** [comment]
Yeah, makes sense, I wouldn't remove the `Component` suffix though, So I think we could choose between

 - `ParticlesComponent`
 - `ParticlesSystemComponent`

Which one looks better? Or any other options?

**Comment by spydon** [comment]
The last one would be `ParticleSystemComponent` in that case I think (without the plural s on `Particle`).

**Comment by alestiago** [comment]
I feel like "System" is such a big word. Personally, who knows what a "System" means in what context! 

I'm more in favour of `ParticlesComponent` since it expresses that it is a `Component` that can have one or more `Particles`; in addition, it's way simpler, shorter and as verbose as `ParticleSystemsComponent`. 

Personally, if I read `ParticlesComponent` over `ParticlesSystemComponent` I find that the latter is somewhat more complex since who knows what do I require to make this `System` work.

In addition, regardless of what naming we go for here, I feel the suffixing `Component` should be mandatory as @erickzanardo raised. 

Btw, do we have any other `Component` with the word `System` in Flame or its packages?

**Comment by erickzanardo** [comment]
Even `ParticleSystemComponent` is longer, I think it makes sense, since particle system is a well know term in game dev, naming it that way will feel more natural to game devs.

> Btw, do we have any other Component with the word System in Flame?

We don't the system word here would be specifically because of this being a particle system.

**Comment by alestiago** [comment]
True! That makes sense, lets's use `System` then. Since it will bring clarity to other game developers using Flame that's a bonus. It might be beneficial also for those that are not used to it and able to link to other resources just from the name.

`ParticleSystemComponent` 👍

**Comment by spydon** [comment]
Closed by #1489
