### ISSUE TITLE
Improve documentation for beginners

### ISSUE THREAD

**Issue by d-apps** [flame-engine/flame#150]
I am a beginner and I'm having so much difficults trying to understand the documentation and how to implement in my project. 

For example, when I tried to add animation to a sprite, the main.dart example just calls the animation directly, but for "best practices" we add the sprite in a "character.dart" a different class for example, but I had no idea how to call from there (and components etc..).

If the examples could be of a real project will help a lot.

I am brazilian and not fluent in english and since there's no documentation in Portuguese, if you guys could provide a more user friendly documentation like JapAlekhin tutorials will help a lot and get more people interested to Flame.

Thank you.

**Comment by erickzanardo** [comment]
I don't know if we should provide tutorials like the ones Alekhin has already written, it would be very redundant, and we even link his tutorials on Flame's README.

His tutorials are very cool for beginners and currently, the best way to start learning Flame.

Flame is an unopinionated framework, so the best practices that apply to a Flame game, is the same ones that would apply to common software development.

I am really not sure what is confusing you, yeah, on the examples we add everything on the main.dart file, but that happens because each example is minimal and about only one subject, so don't need create whole lot of files for that. But  it would be easy to improve from that, you could just wrap a player animation inside a new file, and use that file on your game.

Also, we already have some simple games examples which you can refer to, like this one: https://github.com/flame-engine/flame-example

Finally, we have a channel on Fireslime's discord server where we help people, you can always drop there and ask for help, if you have trouble in english, you can DM me (you can find me by the name CptBlackPixel there), and I can help you in portuguese.

Closing this since Alekhin's tutorials already gives a very good starting point for beginners.

If there is some specific part of the documentation that you think that could be improved, feel free to comment here, open a new issue or let me know on Discord.
