### ISSUE TITLE
Refactor geomerty shape classes

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1521]
Currently, some important `geometry` classes exist only as components: `CircleComponent`, `PolygonComponent`, `RectangleComponent`. I propose to separate their geometrical logic into separate `Shape` classes: `Circle`, `Polygon`, `Rectangle`, allowing these to be reused for various purposes.

Thus, for example, a `CircleComponent` would contain a `Circle` shape, plus some rendering logic to display that shape. At the same time, `Circle` would be responsible for purely geometric functionality, such as determining intersections, whether a point is inside or outside, etc.

**Comment by spydon** [comment]
First we used to have a separate library for this called flame_geom, then I brought it in to the core when doing the first version of the collision detection system, but then in the second version it got so convoluted when I tried to keep them separate (and I got lazy). If you want to give it a go I think it is nicer to have the shape's separates like you suggest, since then they can be used by for example oxygen too.

**Comment by st-pasha** [comment]
:+1:

Do you remember which part in particular got convoluted?

**Comment by spydon** [comment]
> +1
> 
> Do you remember which part in particular got convoluted?

If I remember correctly it was because `absoluteCenter`, `scaledSize` and other `PositionComponent` specific fields like that were used in a lot of the calculations.
