### ISSUE TITLE
TextBoxComponent overwrites lines if the text contains newlines

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1622]
See the screenshot, I've ran our current "Text" example, but added a newline after the first sentence.

<img width="381" alt="Screen Shot 2022-05-13 at 11 38 02 AM" src="https://user-images.githubusercontent.com/4231472/168346389-7acd19c6-cdac-45e5-b8d4-82718f8f0dca.png">

# More information

Are you interested in working on a PR for this?
- [x] yes

**Comment by spydon** [comment]
Aah, I've seen that one before but forgot to create an issue for it i think. Assigned you to it.

**Comment by spydon** [comment]
I think you fixed this, right @st-pasha?

**Comment by st-pasha** [comment]
Not quite: there is a work-around where one can use a `RichTextComponent` to display multi-paragraph text, but that's not quite the same.

**Comment by immadisairaj** [comment]
A normal work-around (for users) would be increasing the `size`. It is probably increasing the width. But, in most of the cases it won't work (when having max width).

From what I see, we are using
```dart
text.split(' ').forEach((word) {
```
to check the number of lines. And this `split` method is not giving the new line.

Let's take an example, `"Hello \n World"` is the text. The output from `split` will be `[Hello, World]` instead of `[Hello, \n, World]`.

The lines calculation itself is not proper at this point. We need a solution where we consider escape characters also.

**Comment by spydon** [comment]
@immadisairaj do you want to work on a PR for this? :)

**Comment by immadisairaj** [comment]
> @immadisairaj do you want to work on a PR for this? :)

Yes, I can start working on a PR for this.
