### ISSUE TITLE
ComposedComponent and Resizable are tricky to use together with base classes

### ISSUE THREAD

**Issue by kurtome** [flame-engine/flame#167]
So bear with me me on this one... I'm not sure if it's really just impossible to simplify due to how inheritance has to work with mixins but I recently spent over an hour trying to figure out why `Resizable.resize` wasn't being called, only to realize it was due to the order of inheritance with `ComposedComponent`.

Essentially, I have a base class called `PhysicalComponent` which most of the objects in my game inherit from. I made `PhysicalComponent` mixin `ComposedComponent` because essentially all of the child classes are composites. 

Then, later on I created my a `Player` which needs to know the screen size for various logic.

```
abstract class PhysicalComponent extends PositionComponent with ComposedComponent {
  ...
}

class TouchInput extends Component with Resizable { 
  ...
}

class Player extends PhysicalComponent with Resizable { 
  TouchInput _input = TouchInput(); 
  
  Player() {
    this.add(_input);
  }
}

class MyGame extends BaseGame {
  BaseGame() {
    final player = Player();
    add(player);
  }
}
```

So the problem is, in the above code `TouchInput.resize` is never called because in `Player` `Resizable.children` shadows `ComposedComponent.children` from the parent class, and then `children()` always returns an empty list!

Anyways, maybe I just shouldn't put `ComposedComponent` on a base class, but maybe there is a way to avoid this problem in the class design of these utility classes?

**Comment by erickzanardo** [comment]
cc @luanpotter

**Comment by luanpotter** [comment]
@kurtome dart mixins become extremely convoluted quickly with the Composed Component, because it needs to override other mixins if they are found, so that is very nasty. One solution would be to make ComposedComponent a proper component, not a mixin. Would that solve your problem? Or do you have a better solution that would work for all cases?

**Comment by renancaraujo** [comment]
Let me hop int the discussion. 
I've recently [updated TRex to the latest flame](https://github.com/flame-engine/trex-flame/pull/5) version, and a felt a lot of this pain. 
I think every component should be able to contain a child.
Another approach could be similar to "render widgets" on Flutter, where we have `MultiChildRenderObjectWidget` and a `LeafRenderObjectWidget`.

**Comment by renancaraujo** [comment]
IMHO tappable and other mixins that are child-awere does too much.

**Comment by erickzanardo** [comment]
This has been inactive for some time now, @luanpotter do you think this can lead to an enhancement or should we close this?

**Comment by kurtome** [comment]
I've been holding off on responding to this because I don't think there is a simple solution...

> One solution would be to make ComposedComponent a proper component, not a mixin

This seems like possibly a good idea although it's bit restrictive. @renancaraujo had the idea of making all components Composed by default, which does feel more natural if you're coming from Unity or something like that.

Overall I think the big design decision takeaway from this is that Mixins shouldn't ever override methods, just add in new methods (with specific enough method names to avoid namespace collision). Otherwise it's just multi-inheritance hell, and and worrying about the "diamond problem"

**Comment by luanpotter** [comment]
I would also like to see @renancaraujo take on this. I particular do not use composable components much, so I never ran into this issue myself. What are the use cases for you guys? Because since component is so abstract, I don't know what advantage composability would have... For example, if PositionComponent was composable that would make more sense (as you can compose position).

**Comment by kurtome** [comment]
> I would also like to see @renancaraujo take on this. I particular do not use composable components much, so I never ran into this issue myself. What are the use cases for you guys? Because since component is so abstract, I don't know what advantage composability would have... For example, if PositionComponent was composable that would make more sense (as you can compose position).

In the one semi-complicated game I've prototyped so far, essentially every component (95%) was a composed position component. Like I made Tile components to be children of the Level Component. And I made the Player component a child of the Level component, and the Player's animation as a child of the Player, etc.

In Unity every component is a position component, and you just ignore the position if you don't need it. Which is a bit weird but also fine?

**Comment by stefankrosell** [comment]
I hope it's OK I leave my two cents: I just started using Flame and found it very strange that I was unable to add children to a component by default. For any game or game-like use, a transform hierarchy is relevant. It's not only Unity - all game (or game like) environments I've worked with does this because it makes sense. Character armor and weapons etc. I recommend you look to pixi.js for more inspiration. Also, you guys rock. :-)

**Comment by luanpotter** [comment]
I'm leaning on either making position component composable by default and every subclass and instance can be composable (and then the other mixins can work around on that) OR making a child of position called composable component with is just a wrapper and then you add stuff inside (like your composable will not be able to be a Sprite component but you can add the Sprite component as a child to your composable).

Any thoughts on either of these two ideas?

**Comment by kurtome** [comment]
I think making `PositionComponent` always composable makes a lot of sense.

There are some instances where I want to compose components just for organizational reasons (like my InputManagerComponent has children that need to update on every frame but are positionless), but I don't mind making those PositionComponents.

**Comment by luanpotter** [comment]
We discussed this and are going forward with a proposal for merging `PositionComponent` and `ComposableComponent`, making it so that every `PositionComponent` can optionally have children. We will add more details soon :) (cc @renancaraujo @erickzanardo)

**Comment by erickzanardo** [comment]
Related issue for reference https://github.com/flame-engine/flame/issues/223

**Comment by kurtome** [comment]
@luanpotter Not sure if this is the right place to raise this idea, but I think some of the fields on `Component` should also be mutable via a widely-used base class (possible `PositionComponent`?)

For example, while waiting for this issue to be resolved, I've been using something like this:

```
abstract class SuperPositionComponent extends PositionComponent
    with HasGameRef, ComposedComponent {

  int loopPriority = 0;

 bool shouldDestroy = false;

  @override
  int priority() => loopPriority;


  @override
  bool destroy() => shouldDestroy;

}
```

Does that make sense to add those fields or am I overcomplicating it, or should they be somewhere else? The benefit of them being mutable on _every_ component, is all components from libraries (like `TextBoxComponent`) would be easier to set their `priority` and destroy them, without having to subclass them.

**Comment by erickzanardo** [comment]
I agree with you @kurtome , although I would suggest removing the method destroy, and leaving only the property.

The priority also is more complicated than that, you can't change it in runtime, as this is used by the internal list of the base game, but it would be nice to have a updatePriority method on components.

**Comment by shinayser** [comment]
Hello everyone!  Just started studying flame and got myself stuck on this compasability problem. Luckly you guys already discussing it here!
Are you guys already working on making PositionComponent composable by default?

There is also something that I found pretty weird is that 'ComposedComponent' needs the 'Tapable' mixin. Isn't that weird? Forcing a class to be tapable just beucase of composability?

**Comment by renancaraujo** [comment]
@shinayser Yes, @luanpotter is working in the composed refactor. Since the changes will be very disruptive, it will aim the `1.0.0` branch.

**Comment by MrMuMu** [comment]
I'm new to flutter, flame, game dev and also what I'm going to suggest probably requires a lot of refactoring/designing. However from prior experience what I'm going to explain feels like the right approach to the problem.

# Option 1
- Add an abstract `GameObject` class which has fixed `PositionComponent`
- Hold a list for other components if the derived class needs to create a complex game object
```
abstract GameObject {
  PositionComponent position;
  List<Component> components;
}

class MyGameObject extends GameObject {
  AnimationComponent animationComponent;
  GameObject() {
    super.components.add(animationComponent);
  }
}
```

# Option 2
- Add an abstract `GameObject` class
- Create mixins for components
- Add mixins to your game object
```
abstract GameObject {

}

mixin PositionComponent on GameObject {
  double x,y;
}

class MyGameObject extends GameObject with PositionComponent {
  GameObject() {
    x = 0;
    y = 0;
  }
}
```

Option 1 feels like safer OOP approach to the problem. I don't think things can get messy but I can see that it may create a lot of boilerplate code.

Option 2 feels very dangerous to me because of mixins. Sometimes mixins seem very cool but when things get big, multi-inheritance creates a lot of problems. But hey, since dart provides such a tool maybe you guys can take advantage of it.

**Comment by erickzanardo** [comment]
This is solved on the v1 branch.
