### ISSUE TITLE
Auto-expand flame menu in the documentation site

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1773]
# What could be improved

Make the "flame" section of the docs auto-expanded when the user first visits the Flame documentation site.

# Why should this be improved

This would let the user see more clearly where the main content is.

# Any risks?
No.

**Comment by immadisairaj** [comment]
There is no default way of doing this using sphinx. But, there is a [workaround](https://github.com/readthedocs/sphinx_rtd_theme/issues/455#issuecomment-1098135033) which can work when loading the page.

I tried it out in local, and it works fine. We can customise it to only expand the "flame" section instead of all sections and sub sections.

But, a limitation is that, the "flame" section is always expanded even when the other sections are expanded ("flame-audio", etc.)

I would like to work on a PR for this.

**Comment by st-pasha** [comment]
You can simply add the script into the home page file `index.md`:
`````
```{raw} html

<script> ... </script>
```
`````

**Comment by immadisairaj** [comment]
Wouldn't that expand only from the current branch and not previous. I think we should be doing the change which works for previous version also.

I have made a commit based on the case I have sent earlier. Can you please look at it => [here](https://github.com/immadisairaj/flame/commit/bbb95dd8eff002822c24f1c8762bb51ab7f53e1c).
I will try to check adding the script inside `index.md` meanwhile.

**Comment by immadisairaj** [comment]
I tried adding the script in `index.md`. It worked fine as expected. I doubt it will work on previous versions of documentation.

The only question now is which one to implement.
1. Add a script to whole doc theme, script runs everything the page loads.
2. Add the script in index file. Which will run only when in index and might not work for previous versions of the documentation.

**Comment by spydon** [comment]
I like the first option, but would your suggestion work when the user isn't coming in to the root page as the first page?
If they'd for example click on https://docs.flame-engine.org/1.2.0/flame_forge2d/forge2d.html the Flame section shouldn't be expanded.

**Comment by immadisairaj** [comment]
Yes, the Flame section won't be expanded then. The only place it is expanded is when it is in the home page of the complete docs site.
