### ISSUE TITLE
How to use textfield?

### ISSUE THREAD

**Issue by KevinAtlans** [flame-engine/flame#182]
How to use the input box in the game?

anybody any suggest?

**Comment by KevinAtlans** [comment]
Oh, maybe i find it!   https://jap.alekhin.io/setup-widget-tree-flame-flutter-game

**Comment by gadgetreviews** [comment]
Hello,

I have same problem. I am developing a game with flame engine. I need to open a text input (textField, textEdit or whatever its name) and ask the user his/her input (player name) as a text in my flame game. How can I do that in flame? 

Thanks for help

PS: I don't understand why OP decided to close this case. Because the link provided 2 years ago did not answer the original queson.

**Comment by wolfenrain** [comment]
@erickzanardo also mentioned this in our discord, but for the sake of archiving I am going to copy his answer here.

If you want to integrate widgets into your Flame game, we recommend using our Overlay API. This allows for overlaying different kind of widgets into your game.

https://github.com/flame-engine/flame/blob/main/doc/game.md#flutter-widgets-and-game-instances

**Comment by luanpotter** [comment]
I also answered this here: https://stackoverflow.com/questions/66743319/how-to-use-textfield-in-a-flame-game

**Comment by juliavi** [comment]
The link above doesn't work

**Comment by spydon** [comment]
> The link above doesn't work

Here is the correct link:
https://docs.flame-engine.org/1.2.0/flame/game.html#flutter-widgets-and-game-instances
