### ISSUE TITLE
(flame_forge2d) provide a `ContactListenerComponent`

### ISSUE THREAD

**Issue by alestiago** [flame-engine/flame#1859]
# Problem to solve
There is a lack of an API to enable doing so. Currently, stacking ContactCallbacks is particularly challenging.

**For example consider solving the following scenario:**
Given body component `A` that contacts  body component `B` and components `C` and `D` which are `A`'s children that want to listen to `A` and `B` contacts.

# Proposal
The main idea is to favour composition over mixin in.

Adding a component such as `ContactListenerComponent` that enables to listen to contacts between two bodies/fixtures.

For example:
```dart
  @override
  Future<void> onLoad() async {
    await super.onLoad();
    await add(
      ContactListenerComponent<A, B>(
        onPreSolve: () {},
        onPostSolve: () {},
        onBeginContact: () {},
        onEndContact: () {},
        children: [
          CircleComponent(radius: 10),
        ],
      ),
    );
  }
```

One could also override `ContactListenerComponent`.

The addition of a `ContactListenerComponent` makes it easier to use the pattern introduced by `flame_behaviors`.

**Comment by alestiago** [comment]
(cc: @spydon , @wolfenrain)

**Comment by spydon** [comment]
I don't think one would like to add a whole level in the component tree just to listen to events, that doesn't seem like a very performant solution?

**Comment by wolfenrain** [comment]
Instead of making it a component, what about a mixin?

It could work the same way as we have the flame collision system. On collision check if the body has a component that `is ContactListenerMixin`, if so trigger that otherwise check for any registered `ContactListeners`. That wouldn't add to the cost of the component tree but would be flexible for any kind of game made with FlameGame.

**Comment by alestiago** [comment]
We already can mix it in, however it only works for one component, since it can only be assigned to a single `userData`. We should defiantly improve on it to allow mixit in with multiple. So indeed, this is something this issue points at. It can be done with a mixin or a component, or both.

Also, I personally feel like the developer experience is better with components over mixins. I do understand there is some performance cost but I'm wondering where do we draw the line. Since, for example, why do we have a `KeyboardListenerComponent`? The `KeyboardListenerComponent` could be refactored and made a mixin, right?

https://github.com/flame-engine/flame/blob/c887c3616e9f65209b8e29cb8575a0052db3e2bb/packages/flame/lib/src/components/input/keyboard_listener_component.dart#L14

**Comment by wolfenrain** [comment]
> Also, I personally feel like the developer experience is better with components over mixins. I do understand there is some performance cost but I'm wondering where do we draw the line. Since, for example, why do we have a `KeyboardListenerComponent`? The `KeyboardListenerComponent` could be refactored and made a mixin, right?

We already have the `KeyboardHandler` mixin that does this btw ;-), but we draw the line at performance, we prefer to optimize for performance over user-ability unless the performance is negligible (which is subjective of it's own)  

> Personally, I think having them as components achieves separations of concerns and integrate better with the patterns showed at [pub.dev/packages/flame_behaviors](https://pub.dev/packages/flame_behaviors). I'm wondering if we could potentially improve the engine in such a way that we can make the API be nice and developer friendly without sacrificing performance.

The patterns from third party packages are not a main concern for the engine it self, as mentioned above we prefer to optimize for performance over user-ability. If a third party package creates an API on top of FCS to allow for something like separation of concerns but at the cost of performance then that is their choice. To me that just shows that FCS is flexible enough already for anyone to make such, indicating that the API is already developer friendly to a degree.

But for this precise problem the issue is more focused on the fact that we would have to go through the component tree to get all the components we need for potential contact callbacks. And while there are ways around that, it would be difficult to maintain and test it (at least that is what I feel).

**Comment by alestiago** [comment]
> But for this precise problem the issue is more focused on the fact that we would have to go through the component tree to get all the components we need for potential contact callbacks. And while there are ways around that, it would be difficult to maintain and test it (at least that is what I feel).

I don't think we need to traverse the tree to do that. We can create a system that avoid traversing by improving the `WorldContactListener`. The game already holds an instance of the world which has this listener. So a `ContactListenerComponent` can register itself.

**Comment by spydon** [comment]
So the most common usecase here is for the `ContactListenerComponent` to pass the information of the callbacks to its children? Or was there a point in having the `children` in the example? 
Or is the usecase just to handle the contacts itself? If so, I don't understand why it needs to be in the component tree, since it isn't dependent on `update` or `render`.

**Comment by alestiago** [comment]
Indeed, `ContactListenerComponent` doesn't need to be on the component tree.

I think we can get rid of the proposed `ContactListenerComponent` and just improve the `ContactCallbacks` listener mixin so that it can be used more than once and with a nice API to detect fixuture contacts only.

**Comment by spydon** [comment]
That sounds much better indeed

**Comment by alestiago** [comment]
@spydon I'll close this issue and open a new one where we can discuss proposed `ContacCallback` API.

Does this sound good to you?
