### ISSUE TITLE
TapDectector and Tapable conflict

### ISSUE THREAD

**Issue by rubberbird** [flame-engine/flame#199]
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-NZ)
flame: ^0.17.2

It seems that there is a conflict between TapDetector and Tapable mixins. 

If I use the TapDetector Mixin with my BaseGame class like below.

`extends BaseGame with TapDetector`

I don't see any tap events registering in my Tapable SpriteComponent. When I remove the BaseGame mixin, everything works.

**Comment by luanpotter** [comment]
@erickzanardo I think you might know the issue here

**Comment by erickzanardo** [comment]
tbh I don't @luanpotter, rubberbird discovered this, and reported on our Discord, and I asked him to open this issue, so we don't forget, but I need to investigate, my guess is that the `TapDetector` mixins is overriding the BaseGame method, removing its behaviour which calls the tapable handlers.

**Comment by erickzanardo** [comment]
@rubberbird I didn't find the solution, but I think I find a workaround. Don't make your game instance use the `TapDetector` mixin, and just override the `onTap*` methods, and make sure to call the `super`.

This effect is happening because `BaseGame` it self includes `TapDetector` and when you make your instance use it too, we create that multi inheritance problem.

We probably need to find a better solution for this, but I will need to give this some thought, but at least there is this workaround.

**Comment by luanpotter** [comment]
@erickzanardo this is fixed by 0.22 right?

**Comment by erickzanardo** [comment]
Yeah
