### ISSUE TITLE
Cannnot set width or height of FlareComponent

### ISSUE THREAD

**Issue by stefankrosell** [flame-engine/flame#202]
I assume width and height should be passed on to internal _flareAnimation

**Comment by FrankenApps** [comment]
Not sure if I understand correctly, but I am able to set width and height like this:
`FlareAnimation myAnimation  = await FlareAnimation.load("assets/myAnimation.flr");
myAnimation.width = 50;
myAnimation.height = 30;`

However the location seems to be influenced by this action, because
`myAnimation.x = 300;
myAnimation.y = 80`
moves in a strange way, if the size is changed.

It's even worse, when you have two FlareComponents in your view, as they seem to influence each others position.

**Comment by stefankrosell** [comment]
FlareAnimation can be rescaled, but FlareComponent does not respond to new values for width or height.

**Comment by luanpotter** [comment]
@erickzanardo wanna take a look?

**Comment by erickzanardo** [comment]
I should be looking into this tonight.

**Comment by stefankrosell** [comment]
Great! It would also be very nice to have "updateAnimation" available in the component.

**Comment by erickzanardo** [comment]
This should be fixed by #210

**Comment by erickzanardo** [comment]
Fixed on #210, a new version should be shipped soon with this fix, stay tuned for the next release.
