### ISSUE TITLE
MoveToEffect, RemoveEffect and SpeedEffectController not working inside SequenceEffect

### ISSUE THREAD

**Issue by juanoboif25** [flame-engine/flame#2096]
# Current bug behaviour

When i put a `MoveToEffect` with a `SpeedEffectController`and a `LinearEffectController` and also a `RemoveEffect` inside a `SequenceEffect`, the component subject to them doesn´t move but instantly teleports to the desired `Vector2` (regardless of what `speed` i specify) and it doesn´t get removed from the game. If the Speed and Linear `EffectController`'s get replaced by a `EffectController` object, the component does move in a trasition-like manner. Taking them out of the `SequenceEffect` resolves all of the unexpected behaviours, regardless of what controller i use.

# Expected behaviour

Move the component to a desired `Vector2` in a timely manner and then removing it from the game.
# Steps to reproduce

Add a `SequenceEffect` containing a `MoveToEffect` and a `RemoveEffect` to a `PositionComponent` in my case a `CircleComponent`,
use `SpeedEffectController`and a `LinearEffectController` for the `MoveToEffect`

# Flutter doctor output

```
Output of: flutter doctor -v
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.22000.1098], locale en-US)
    • Flutter version 3.3.4 on channel stable at REDACTED
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (2 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at REDACTED
    • Platform android-31, build-tools 31.0.0
    • Java binary at: REDACTED
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

    • Pixel 3a XL (mobile) • 93WAX0BHDF • android-arm64  • Android 12 (API 32)
    • Windows (desktop)    • windows    • windows-x64    • Microsoft Windows [Version 10.0.22000.1098]
    • Edge (web)           • edge       • web-javascript • Microsoft Edge 106.0.1370.42

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

# More environment information
* Flame version: 1.4.0
* Platform affected: android (haven't tested any other)
* Platform version affected: android 12 (haven't tested any other)

**Comment by munsterlander** [comment]
Ok, I took a bit of time to look at this and can confirm something is going on, but it is not based on the `MoveToEffect`.  The issue stands with the `SpeedEffectController`, because if you open the test for that controller, the linter automatically flags all the tests as invalid that its missing `duration` as a defined parameter.  I created a test file and I had it pass linting once and then it had a runtime error and after modifying the file, I could never get it to pass linting again:

```
add(
          SequenceEffect([
            MoveEffect.to(
              Vector2(30, 50),
              SpeedEffectController(
                LinearEffectController(1.0),
                speed: 1.0,
                duration: 1.0,
              ),
            ),
            MoveEffect.to(
              canvasSize / 2,
              EffectController(duration: 0.5),
            ),
          ]),
        );
```

If you copy the example from the docs, it does not work as written either.

**Comment by munsterlander** [comment]
Ok, so after putting this together, this works fine but it does not remove the component.

```dart
import 'package:doc_flame_examples/flower.dart';
import 'package:flame/effects.dart';
import 'package:flame/experimental.dart';
import 'package:flame/game.dart';

class SequenceEffectGame extends FlameGame with HasTappableComponents {
  @override
  Future<void> onLoad() async {
    final flower = Flower(
      size: 40,
      position: canvasSize / 2,
      onTap: (flower) {
        flower.add(
          SequenceEffect([
            MoveEffect.by(
              Vector2(30, -50),
              SpeedEffectController(
                LinearEffectController(1.0),
                speed: 10.0,
              ),
            ),
            RemoveEffect(delay: 1.0),
          ]),
        );
      },
    );
    add(flower);
  }
}

```

**Comment by st-pasha** [comment]
Thanks for checking @munsterlander. It means there are probably 2 different bugs here: one with the RemoveEffect, and another with the MoveEffect.

**Comment by munsterlander** [comment]
Well, I should add, the error is only with that controller. Other controllers work correctly - see the existing sequence effect live example.

**Comment by tksoh** [comment]
[disclaimer: I am new to flutter]

I traced into apply() of RemoveEffect which tries to remove it's parent. But when wrapped within SequenceEffect, its parent is not the component, but SequenceEffect itself. I'm not sure what would happen if there are more effects after RemoveEffect, though I'd believe they will just be ignored since SequenceEffect has been removed?

>      parent?.removeFromParent();

For now I just utilize the onComplete callback to remove the component manually. Not the best solution, but allow me to move on.

**Comment by spydon** [comment]
You are completely correct @tksoh, it should be using `target` and not `parent`.
I'll write up a PR for it.

**Comment by pgirald** [comment]
Hey @spydon, I just saw that the mentioned `SpeedEffectController` problem was not addressed. In fact, I noticed that such controller does not work since (in the `Effect`'s `advance()` method) the `MoveToEffect`'s `onStart()` method does not get executed before the `advance()` controller's method does:

```dart
@internal
  double advance(double dt) {
    final remainingDt = controller.advance(dt);//<--`advance()` executes first
    if (!_started && controller.started) {
      _started = true;
      onStart();//<--then `onStart()` is executed
    }
    if (_started) {
      final progress = controller.progress;
      apply(progress);
      _lastProgress = progress;
    }
    if (!_finished && controller.completed) {
      _finished = true;
      onFinish();
    }
    return remainingDt;
  }
```
So `SpeedEffectController` gets 0.0 from the `moveToEffect`'s `measure()` method. So I simply changed the order:

```dart
@internal
  double advance(double dt) {
    if (!_started && controller.started) {
      _started = true;
      onStart();//<--first `onStart()` is executed
    }
    final remainingDt = controller.advance(dt);//<--then `advance()` executes
    if (_started) {
      final progress = controller.progress;
      apply(progress);
      _lastProgress = progress;
    }
    if (!_finished && controller.completed) {
      _finished = true;
      onFinish();
    }
    return remainingDt;
  }
```
In fact, that's the order you use in the `update` method, and that's why `SpeedEffectController` works outside a sequence effect.

**Comment by spydon** [comment]
@pgirald good catch! Do you want to put up a PR for that?
