### ISSUE TITLE
New Input System: continuePropagation should be true as default

### ISSUE THREAD

**Issue by egorderg** [flame-engine/flame#2232]
# What could be improved
The continuePropagation flag should be true as default.

# Why should this be improved
Reduces boilerplate code where you just need to set continuePropagation to true.
JS also uses stopPropagation and in the defold engine it's also propagated until the user returns true.

# Any risks?
No

# More information

**Comment by spydon** [comment]
Agree that this would be a good change for V2, what do you think @st-pasha and @flame-engine/flame-admin?

**Comment by st-pasha** [comment]
@egorderg Can you please describe what do you think the potential use-cases be when `continuePropagation` should be set to true?

Reducing boilerplate is of course a good goal, but we must understand that changing the default value of the flag will shift the boilerplate to the cases where that flag is not needed. So we ought to compare the frequency of these different use-cases.

**Comment by egorderg** [comment]
One of the problems for me are siblings. I have multiple views like SceneManager, DialogManager, DebugView where only the last Component gets the events. This constellation with multiple siblings is common in my opinion.
But i also think that in some cases a propagation in not needed and can hurt the performance because of the iteration of the components e.g. Game -> SceneManager -> Scene -> Board, where i only want the board the receive the events and don't care about the others. So if i want the Scene to get the event because the Board has a DragCallbacks it's not boilerplate code because i already have a implementation in the Board component.
The boilerplate code in my code currently occurs only in components that are siblings.

**Comment by egorderg** [comment]
Or the continuePropagation should only work in the vertical hierarchy, so siblings always get their input event and continuePropagation is only used to move it to the parents.

**Comment by st-pasha** [comment]
In the new event system, the touch/drag events are delivered according to the visual hierarchy of the components. For example, suppose you have the component tree `Game -> SceneManager -> Scene -> Board -> Piece`, where the last 3 components are `with TapCallbacks`. If the user taps somewhere within the board, then the event will first be delivered to whichever element is rendered at the point of tap. Say, it's a `Piece`. Or, if the user didn't tap on any piece, then the event will be delivered to the `Board`. Or, if the user didn't tap anywhere within the board, then the event will be received by the `Scene`.

This is the default behavior. Within the `Piece` component you can set `continuePropagation=true`, and then the event will be also delivered to the `Board`. This might be exactly what you need, but it seems to me that in a large number of cases, a more useful default is to have `continuePropagation=false`, which would make the tap event delivered to `Piece` only.

Note also, that if you want the tap events to only be delivered to `Board`, and never to `Piece`s or to the `Scene`, then simply don't add `TapCallbacks` to those other components.

**Comment by spydon** [comment]
I wonder which use-case is the most common, it feels like it would be to not propagate further down.

But for siblings I think it is probably the opposite, that the most common use-case would be that all siblings with the same priority would get it. It would be hard to handle that use-case separately though.

So I think I have changed my opinion, the current default is probably good.

**Comment by st-pasha** [comment]
> But for siblings I think it is probably the opposite, 

That's a bit too abstract though, isn't it? Let's look at some concrete examples.

- Suppose you have a `Board` with multiple chess `Piece`s. Those pieces are sibling components. However, they will always be placed in such a way as to not overlap, which means that at any given point of the screen there could be only at most one `Piece` -- thus, propagation is useless.
- Ok, what if we have a card game, with many `Card`s on the `Table`. The cards are siblings here, and they often overlap. The user may tap a card to flip it, or grab it for dragging. However, in this case we'd want a tap to flip only one card, not all the cards underneath. And same for dragging (sometimes there is a functionality to drag a stack of cards -- but even in that case the `onDragStart` event shouldn't be propagated, instead the set of cards being dragged is decided by checking which cards are "on top" of the one that received the event).
- Another case: a game with an isometric map, like Fallout or StarWars. The units can visually overlap here due to the isometric projection. The user may click a unit in order to select it (if friendly), or attack (if hostile). Again, you'd want a single click to select a single unit only, and your units to attack a single enemy target. So, no event propagation is needed.
- The OP gives the example of `SceneManager`, `DialogManager`, `DebugView` siblings -- but these are actually organizational components, they shouldn't be handling taps/drags at all, since they don't have a visual representation of their own. So in this case these components would simply NOT handle taps/drags at all, and once again propagation is unnecessary.

So, propagation is actually kinda rare case. Like, maybe you have a game where you tap to shoot, and your weapon has "piercing" bullets that may go through the front enemy and also hit somebody behind. But even in this case, there'd be some logic for what kind of bullets you currently have, and how many enemies were already pierced. So, the logic would need to propagate _sometimes_ but not always. Thus, it wouldn't even matter for this use case what the default value of `continuePropagation` flag is.

I'm not trying to cherry-pick anything here, I just can't think of any good use-case where tap/drag event propagation would be a sensible default. Am I missing something?

**Comment by spydon** [comment]
The type of games I was thinking about was the classic "fly/bug squasher" games, where you press on the screen as fast as possible to kill as many creatures as you can, even when they overlap. There are probably more games too, but I think we can keep the default like it is for siblings too since you had a pretty exhaustive list for other types of games and those use-cases ought to be more common.
