### ISSUE TITLE
Animation.sequenced from any image object

### ISSUE THREAD

**Issue by rapus95** [flame-engine/flame#248]
To support loading sprite sheets from the internet it'd be easiest if you could pass any object that can be created by `Image`
`Animation.sequenced(Image.network("myurl"), args...)`

**Comment by erickzanardo** [comment]
You mean this? https://api.flutter.dev/flutter/widgets/Image/Image.network.html

**Comment by rapus95** [comment]
Exactly!
Looks like you only need to add a constructor which uses the `Sprite.fromImage` function inplace of the `Sprite(...)` constructor

**Comment by erickzanardo** [comment]
That is not that easy, this is a Widget, the Image that we use is an class from the dart:ui library, which really represents an Image, and not an widget, I don't know how easy would it be to draw an Image widget into the canvas.

**Comment by erickzanardo** [comment]
@luanpotter @renancaraujo what are your thoughts about this? I am not sure about this.

**Comment by rapus95** [comment]
You misunderstand me.
Currently, `Animation.sequenced("filepath", 8)` instantiates the sprites from a local file (i.e. `Sprite("filename",args...)`). I suggest to have another constructor: `Animation.sequencedImage(...)` which is a copy of the current `sequenced` function but which calls `Sprite.fromImage(img, sameargs...)` instead of `Sprite("filename", args...)` and by that loads the sprites from an image object rather than a file name. That reduces the amount of remote accesses in case of the network variant.

**Comment by erickzanardo** [comment]
@rapus95 I see, that is totally possible, I was understanding that you wanted to use the Image Widget inside the animation here.

Sorry for the confusion. Gonna mark this an an enhancement and will do when possible, or if you want, feel free to submit a PR.

**Comment by rapus95** [comment]
It'd also be helpful if `sequenced` supports `cacheHeigth` and `cacheWidth` as otherwise sprites can easily crash the system :/

**Comment by renancaraujo** [comment]
Found this at the bottom of my notifications, sorry for the ridiculous delay.

We cant mix widgets with flame components (for now), so we could receive an [`ImageProvider`](https://api.flutter.dev/flutter/painting/ImageProvider-class.html) instead of the Image widget as proposed initially in this issue. 
ImageProvider has as subclasses [`NetworkImage`](https://api.flutter.dev/flutter/painting/NetworkImage-class.html), `FileImage` and so on.
**BUT** retrieving a dart_ui Image from an ImageProvider [is an async process](https://github.com/renancaraujo/photo_view/blob/master/lib/photo_view.dart#L399). The `Image` widget manages a loading state before rendering, and so have we.

So here we have the two pills: We can create `.sequenced` as an async static method delegating the control of loading state to the engine users OR we can make it a normal constructor and manage loading state internally (I.E: render nothing while the image loads).

I like the former pill.

**Comment by erickzanardo** [comment]
This will be addressed on the v1 on the task I am working on

**Comment by erickzanardo** [comment]
Solved for the v1.0.0
