### ISSUE TITLE
suggestion: repo self contained tiled.dart

### ISSUE THREAD

**Issue by bung87** [flame-engine/flame#249]
season 1:
Improve the original tiled.dart
my current need:
need the tiled.dart layer store tiles in 2d list so I can easily have `getNeighboursOf` method which used in path finding.
``` dart 
var tiles = new List<TerrainTile>();
    [Direction.LEFT, Direction.UP, Direction.RIGHT, Direction.DOWN]
        .forEach((element) {
      var t;
      try {
        t = _cachedTiles[node.x + element[0]][node.y + element[1]];
      } catch (e) {}
      if (t != null) {
        tiles.add(t);
      }
    });
```

and see my commits https://github.com/bung87/tiled.dart/commit/a13da7c6339d0c6bcb022c13c35548602cb616bd  

I also need set the map offset by tiled map coordination and pointer position. somelike `centerTo`

season 2:
Provider more tiled orientation see  
https://github.com/kendalharland/tile_system

this repo just for inspire, we can consider implement it in tiled.dart lib.
season 3: 
Improve `TiledComponent` work with these together.

**Comment by erickzanardo** [comment]
Improve can be quite a lot of things, what you want to be improved here?

This repository you sent don't look to have any relation with the Tiled format, what is idea?

Provide a better and meaningful description of your suggestion, or even better, send us PR with your ideas, otherwise we can't do much.

**Comment by bung87** [comment]
hi I update my description, explained my idea.
