### ISSUE TITLE
Set grid on NineTileBox

### ISSUE THREAD

**Issue by projectitis** [flame-engine/flame#2490]
# What could be improved
Allow the user to manually set the nine-tile grid sizes.

# Why should this be improved
In many cases the user needs to use a grid size other than the default 1/3 3x3 grid.

# Any risks?
Not that I can see. I have implemented and tested it in my own project and works well.

# More information
I have implemented the feature already. [See changes here](https://github.com/flame-engine/flame/compare/main...projectitis:flame:feature/ninetilebox-set-grid)
Any feedback helpful, especially:

- Are the asserts overkill? I could instead adjust the user values to fit without overflowing
- Where to add tests?
- Update example [here](https://github.com/flame-engine/flame/blob/main/examples/lib/stories/rendering/nine_tile_box_example.dart), or create new?
- Aside from update, any change to [docs](https://github.com/flame-engine/flame/blob/main/doc/flame/components.md#ninetileboxcomponent) required?

**Comment by spydon** [comment]
Good stuff, please put it up as a PR. :)

> Are the asserts overkill? I could instead adjust the user values to fit without overflowing

Since you have already written them and they give some value to the user I think they can be kept.

> Where to add tests?

You can add a new file here: https://github.com/flame-engine/flame/tree/main/packages/flame/test/components
It doesn't seem like the `NineTileBoxComponent` has any tests yet, only the widget.

> Update example here, or create new?

I think you can create a new one to not cram to much stuff into the existing example.

> Aside from update, any change to [docs](https://github.com/flame-engine/flame/blob/main/doc/flame/components.md#ninetileboxcomponent) required?

Just explain how to use the newly added method.

Some other comments:
 * We don't allow abbrevations like `rightCol`, write out the full words.
 * It would be good to be able to set this directly from the constructor, so maybe create a class that contains these values (`{int? leftCol, int? rightCol, int? topRow, int? bottomRow}`) that can be passed in?
 * The method's dartdoc could explain a bit more what it does.
