### ISSUE TITLE
`Anchor` methods should not create new `Vector2` objects

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#2543]
# What could be improved
We shouldn't create new `Vector2` objects in the `Anchor` methods.

# Why should this be improved
To improve performance.

# Any risks?
No, just make sure there are proper tests.

# More information
https://github.com/flame-engine/flame/pull/2538#discussion_r1199839159

**Comment by immadisairaj** [comment]
Haven't got the exact meaning of the comment there.

Do you mean to point that `toVector2()` is creating new vectors and and it should be minimised?

So, we could do operations and then create one `Vector2` instead of two different things? or you think to entirely return just one new Vector2?

Some possible solutions I can currently think of:
Sol1: creates in total of 2 new vectors (one from using `+` operator and other we are creating)
```dart
return position +
          (Vector2(otherAnchor.x - x, otherAnchor.y - y)..multiply(size));
```

Sol2: creates in total of 1 new vector (as we are calculating everything beforehand)
```dart
final resultX = position.x + ((otherAnchor.x - x) * size.x);
final resultY = position.y + ((otherAnchor.y - y) * size.y);
return Vector2(resultX, resultY);
```

**Comment by spydon** [comment]
> Do you mean to point that toVector2() is creating new vectors and and it should be minimised?

Yes, because if these methods are used from the update-loop it will negatively affect performance.

You can do solution 1 without creating two vectors too:
```dart
return Vector2(otherAnchor.x - x, otherAnchor.y - y)..multiply(size)..add(position);
```

**Comment by immadisairaj** [comment]
Yeah right.. I can send a PR for it right away. If this is the only change that is needed.

**Comment by spydon** [comment]
That would be great, also check that there aren't any other unnecessary vectors created in that class, since this issue is regarding the whole class. :)
