### ISSUE TITLE
Tiled asset loader

### ISSUE THREAD

**Issue by CodeDoctorDE** [flame-engine/flame#2568]
# Problem to solve

I want to give users in my app the option to create their own maps. For this I want to sandbox the asset loading process.

# Proposal
Create an asset loader argument, for example with `(String path) => Uint8List` to get the image.

# More information

This feature can also has the feature to create multiple asset directories for different levels.

**Comment by spydon** [comment]
What you can do is put up a PR that let's you pass in an `Images` cache through the chain so that it can be used [here](https://github.com/flame-engine/flame/blob/main/packages/flame_tiled/lib/src/renderable_layers/image_layer.dart#L77), instead of it using the default cache. The cache can set restrictions on which the root of the cache is.
