### ISSUE TITLE
Allow possibility of `CameraComponent` without a world

### ISSUE THREAD

**Issue by ufrshubham** [flame-engine/flame#2614]
# What could be improved

As of now the `CameraComponent`'s API strictly needs a world while creation. But its code makes explicit checks if the world `isMounted` before accessing it. This means camera can already live without a world.

# Why should this be improved

This is not a huge deal breaker, but if we allow world to be nullable, it opens up the possibility to drop `late` in following case:
```dart
class MyGame extends FlameGame {
  late CameraComponent camera; // can be made `final camera = CameraComponent();`

  @override
  Future<void> onLoad() async {
    final world = await loadMyWorld();
    await add(world);

    camera= CameraComponent(world: world); // can be made `camera.world = world;`
    await add(camera);
  }
}
```

# Any risks?

This will be a breaking change for all the projects that access world from the `CameraComponent` as it will now be a nullable.

# More information

If this is an acceptable chance, I can work on this.

**Comment by spydon** [comment]
Sounds good to me, since the world is already exchangeable, why not being able to change it to not looking at a world. :)
I'm currently exploring how to create a `Forge2DGame` with a built-in `CameraComponent` and this would make that code a little bit nicer too. (Later that will also be in `FlameGame`).

I'll assign you to the issue.

**Comment by PickleCubeSoftwareLtd** [comment]
@spydon did you managed to get the camera component playing nicely with a Forge2D world? I'm currently struggling with this...

**Comment by spydon** [comment]
> @spydon did you managed to get the camera component playing nicely with a Forge2D world? I'm currently struggling with this...

I have a branch that I'm fixing this on, but it won't be merged for another two weeks or so because I'm way too busy with [Flutter & Friends](https://flutterfriends.dev) at the moment. :/
You can try the branch if you want to, but it is only half done: https://github.com/flame-engine/flame/tree/spydon/move-forge2d-to-cameracomponent
