### ISSUE TITLE
ParticleSystem widget

### ISSUE THREAD

**Issue by subzero911** [flame-engine/flame#2840]
There are currently no particle systems in Flutter, except `confetti` (which is commonly used and quite abused) and `newton_particles` which is weak and has only basic features.
Flame has a solid particle system.
But they can't be used outside of a `GameWidget` instance.

How about adding an independent ParticleSystem widget, allowing to render particles anywhere on the screen, without having a Flame viewport?

Or, I have an another idea: add an option to make a transparent background in a GameWidget. So we can see the widget tree through it. And to draw particles in a GameWidget.
But it looks heavy to have a Flame engine instance just to have a particle effect.

**Comment by spydon** [comment]
You can already set the `FlameGame` background to transparent by overriding the `backgroundColor`:
```dart
class MyGame extends FlameGame {
  @override
  Color backgroundColor() => const Color(0x00000000);
}
```
>  But it looks heavy to have a Flame engine instance just to have a particles effect.

It shouldn't be more heavy than to just drive it manually (or not noticeably heavier at least).

So you can just put your `GameWidget` on top of the rest of your app with a `Stack`.

You could also quite hackily let your particles draw outside of the size of the game, since it isn't doing any cropping by default (like most other Flutter widgets).

**Comment by subzero911** [comment]
Cool!
I would probably want to place my GameWidget in the middle of the Stack. So the particles would be drawn on top of some widgets and below others.
Is it possible?

**Comment by spydon** [comment]
> Cool! I would probably want to place my GameWidget in the middle of the Stack. So the particles would be drawn on top of some widgets (like decorations) and below others (like input fields). Is it possible?

Sure, the `GameWidget` is like any other widget, you can place it anywhere you'd like in the widget tree.
