### ISSUE TITLE
Rationale behind basic rendering and render loop components

### ISSUE THREAD

**Issue by erf** [flame-engine/flame#294]
I'm curious about some basic elements in Flame.

Especially the design choice behind `RenderBox` for `GameRenderBox` and it's use of `RenderBox with WidgetsBindingObserver` to render the game. And also the use of `EmbeddedGameWidget` which inherits from `LeafRenderObjectWidget`.

Also the use of `SchedulerBinding.instance.scheduleFrameCallback(_tick)` to schedule updates. I wonder if you considered something else, like a `Stream.periodic` to do the updates, and then have `StreamBuilder` to rebuild a game widget? Or a Ticker?

Btw the `WidgetBuilder` with the `GestureDetector`, seem a bit _wild_ with all the checks, maybe it could be done different.

Anyways, i'll love to have some of the design choices behind those basic component for rendering and updates explained. Maybe it could be added to the docs.

Thanks!

**Comment by erickzanardo** [comment]
I am gonna answer the things that I can, others I will leave for @luanpotter to complement.

> Especially the design choice behind RenderBox for GameRenderBox and it's use of RenderBox with WidgetsBindingObserver to render the game. And also the use of EmbeddedGameWidget which inherits from **LeafRenderObjectWidget.**

That structure was tailored through time to cover a number of scenarios, specially the `LeafRenderObjectWidget` which was needed to make it easy to add Flame animations as widgets. I remember @renancaraujo worked on this, maybe he can explain a little better.

> Also the use of SchedulerBinding.instance.scheduleFrameCallback(_tick) to schedule updates. I wonder if you considered something else, like a Stream.periodic to do the updates, and then have StreamBuilder to rebuild a game widget? Or a Ticker?

A game engine relies on active rendering, and rendering as much as you can, to that, we need to use something that will enable us to that, and using the Flutter render loop does that for us, if we used a Stream or something like that, I don't the perfomance on some cases would be the same, this is kind the equivalent as the [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestAnimationFrame) used on browsers to make games.

> Btw the WidgetBuilder with the GestureDetector, seem a bit wild with all the checks, maybe it could be done different.

I don't like those checks as well, but it was needed because of the nature of the `GestureDetector` widget, which can conflict if some of the detectors are set at the same time. But this is probably going to be refactored as we re writing this to support multi touches.

**Comment by luanpotter** [comment]
I agree with Erick, this structure has evolved and improved over time to the current state. There is not much a reason for it other than it works very well. We are open to tweaks as long as they make sense and improve something tangible.

About the scheduler, it's totally different than scheduleTick, because scheduleTick does not have a fixed time interval. It tries to maintain 60fps but it will automatically handle slowing it down as needed in case it cannot keep up. So games can run on older devices fine at 30fps for example.

**Comment by erf** [comment]
@erickzanardo what do you mean by `Flame animations as widgets`? Animation components seem to be rendered as other components and sprites? I'm curious as to not just use a `CustomPainter` and a `WidgetsBindingObserver`.

@luanpotter do you mean that `Stream.periodic` is different than `scheduleFrameCallback`? A `Ticker` is using `scheduleFrameCallback` so i think it could replace it for a simpler implemenation.

**Comment by erickzanardo** [comment]
@erf You sure can use CustomPainter, indeed I use it all the time when I don't need things very complicated, but you can also embedded Flame animations as widgets, check this: https://medium.com/flutter-community/sprite-sheet-animations-in-flutter-1b693630bfb3

**Comment by erf** [comment]
@erickzanardo thanks. I found a couple of examples now. i wonder if performance is less when using `CustomPainter` vs `RenderBox` ..
