### ISSUE TITLE
Need an example game of flame-jenny

### ISSUE THREAD

**Issue by HarrisonQi** [flame-engine/flame#2984]
# What could be improved

Flame Jenny is pretty good framework for dialogues, thank you for create this framework, I need this. But I cost too much time to learn it. (The progress is still slow, and it even takes time to learn a new development language for me.)

Need an example game of flame-jenny, or a tutorial doc. 

# Why should this be improved

Document is too difficult for starter, because here only "APIs". I can only learn the implementation and usage from scratch by reading the source code, which is not very friendly to a framework.

Yarnspinner official website only support unity tutorial, it's too difference between them.

# Any risks?

Only an example project. Because other packages exist examples, I learn others so quickly.

# More information

The difficulty I am currently encountering: 
I need to achieve a simple click on the screen, Jenny enters the next dialogue line, and the screen renders the corresponding character image and text. Include listeners on various nodes (such as conversation completion, function calls).

I am learning through the test package of flame-jenny. Currently, jenny runner types out all the dialogues when start... 
Can you give me some advice? 

Thanks again from the bottom of my heart 🧡

**Comment by HarrisonQi** [comment]
I found a tutorial repo, contains jenny: [https://github.com/codetricity/jenny_tutorial](https://github.com/codetricity/jenny_tutorial) (by [codetricity](https://github.com/codetricity))

This repository contains some instructions and video tutorials that have been very helpful to me. However, we still need an official documentation or tutorial. If I completely master this framework in the future, I will submit a tutorial pull request. But before that, it is still necessary to have an expert who has a better understanding and mastery of the framework to write it.🫡

**Comment by spydon** [comment]
We would be very happy to get a Jenny example and docs once you have learned it @HarrisonQi! :blue_heart:

**Comment by codetricity** [comment]
@HarrisonQi when you write the tutorial, can you send me a note?  For example, you could open an issue on that repo that you linked to above.  I made the videos in the repo for my daughter.  She built a nice game about a boy and girl meeting on a subway in Tokyo and then finding out they live in the same apartment complex.  My daughter has since moved on to other things and I haven't looked at flame in a while.  However, I would like to take another look at Jenny since I'm sure it's evolved a lot.   It's a fun hobby, but unfortunately, my daughter is growing up and is now busier than I am.  Though, maybe I built more videos she would go through them and somehow find the time.

**Comment by xjyribro** [comment]
Hi everyone, a bit of a delayed response, but I wrote 2 articles detailing how to use the simple and advanced features of the Jenny API: [Part 1, simple](https://medium.com/@limcheekeen.63/integrating-dialogues-with-flame-part-1-0b4328efd4a6) and [Part 2, advanced](https://medium.com/@limcheekeen.63/integrating-dialogues-with-flame-part-2-a7b6e7e5cbd7). 

Hope it helps!

**Comment by spydon** [comment]
That's great @xjyribro, I'll post those on our articles channel on Discord!
I'll keep this issue open though, since we need some Jenny examples in our own docs too.

**Comment by xjyribro** [comment]
@spydon 
I'd be happy to work with @HarrisonQi to produce a simple example if he has already started on it. I can provide my art assets and code.

**Comment by xjyribro** [comment]
@spydon 
I'm starting to do the Jenny demo. Is there any examples I can refer to? I've not used Melos and Dashbook before. 

My plan is to create a working minimal Flutter app and copy the whole root folder in to `./packages/flame_jenny/jenny/lib`. Would this work?

**Comment by spydon** [comment]
> @spydon 
> I'm starting to do the Jenny demo. Is there any examples I can refer to? I've not used Melos and Dashbook before. 
> 
> My plan is to create a working minimal Flutter app and copy the whole root folder in to `./packages/flame_jenny/jenny/lib`. Would this work?

If you're using flame_jenny you can put the example in `/packages/flame_jenny/example`, but it would be good to have just a super simple example there and then a more complex one in `/examples/`.

You can see how to set up Melos I'm the contributors guide:

**Comment by xjyribro** [comment]
ok thanks! Working on it. Will take a few weeks.

**Comment by spydon** [comment]
> ok thanks! Working on it. Will take a few weeks.

Super, tell me if you need any guidance.

**Comment by spydon** [comment]
Thanks to @xjyribro, there is now an example of how to use flame_jenny :)
https://examples.flame-engine.org/#/FlameJenny_Advanced%20Jenny%20example

~~We should add a small flame_jenny documentation section too, I think most things about Jenny are already covered [here](https://docs.flame-engine.org/latest/other_modules/jenny/jenny.html), but another section under "Bridge Packages" would be good too, where we explain the Jenny Flame components and how to use them.~~

Since there are no components in flame_jenny currently I think we can close this.
