### ISSUE TITLE
Adding more addCommand methods to YarnProject's CommandStorage

### ISSUE THREAD

**Issue by frantovar** [flame-engine/flame#3034]
# Problem to solve
Giving the ability to define commands with more than 3 arguments. 

# Proposal
Having an **addCommand4** and **addCommand5** would reduce this limitation and give more flexibility to use user-defined commands.

# More information
If the feature looks interesting I can work on a PR.

**Comment by spydon** [comment]
Maybe a method similar to `Object.hash` could be added, so that one could pass in a lot of arguments without having to have one method for each number of arguments. The downside is that the type safety is lost.
https://api.dart.dev/stable/3.2.6/dart-core/Object/hash.html

I'll assign you to the issue and you can choose how to implement it.

**Comment by frantovar** [comment]
Hi @spydon, It sounds great but I'm afraid I don't have enough knowledge to solve it the way you propose. I could extend the functionality by adding **addCommand4** and **addCommand5** until a better solution is found. Do you think it could be suitable?

**Comment by spydon** [comment]
Sure, go ahead! I can add the other method later.

**Comment by spydon** [comment]
Closed by #3035
