### ISSUE TITLE
Doc: In ValuerRoute example you can click the transparent area to spawn multiple route

### ISSUE THREAD

**Issue by steambap** [flame-engine/flame#3143]
### What could be improved

ValuerRoute example can be fixed by using a solid background.

### Why should this be improved

The example's behavior is incorrect. It shouldn't spawn multiple value route on top of each other.

### More information

https://docs.flame-engine.org/latest/flame/router.html#overlayroute

### Other

- [ ] Are you interested in working on a PR for this?

**Comment by spydon** [comment]
I don't understand whether this example is about `ValueRoute` or `OverlayRoute` since the description says `ValueRoute`, but the link is leading to `OverlayRoute`. The example for the `OverlayRoute` doesn't include anything that is opening that route and I can't replicate the behavior you are mentioning for the `ValueRoute`. However, if you don't want events to bubble down to the layers behind the route, just set the route to opaque as described in the first section of the docs that you linked.

**Comment by steambap** [comment]
Sorry, I copied the wrong link. I'm talking about `ValueRoute`.

<img width="306" alt="Screenshot 2024-05-03 at 09 15 23" src="https://github.com/flame-engine/flame/assets/9855651/225150f9-87f7-42b4-acb7-48728cb0b627">

If you click semi-transparent area, another ValueRoute will popup.

**Comment by spydon** [comment]
Ah right, now I can reproduce it. That route should indeed be opaque.
