### ISSUE TITLE
drop frame at  windows10 

### ISSUE THREAD

**Issue by DAN-AND-DNA** [flame-engine/flame#326]
flame is awesome, thanks!
I build the "debug example" of flame through go-flutter and offical desktop,  I found they all drop frame （always  at 48fps-52fps）.
but when I start up an another  process which is writen by golang, the game will run fine ( 60fps):
  1 package main
  2
  3 import (
  4     "time"
  5 )
  6
  7 func main() {
  8     for {
  9         time.Sleep(60* time.Millisecond);
 10     }
 11 }

my cpu is i5-9600k, gpu is uhd 630 , system is windows10 ，flame ^0.20.2, Flutter 1.19.0-2.0.pre.15 master branch

**Comment by erickzanardo** [comment]
This is probably something due to the desktop platforms, Flame implements nothing regarding "render" perfomance, all that is used on it, is provided by Flutter, and the engine it is running.

So there isn't much we can do here to improve that, we need to wait those platforms became more stable, as Desktop support still is very experimental/beta.

You can see on this [issue](https://github.com/go-flutter-desktop/go-flutter/issues/59#issuecomment-473817242) on go-flutter project, that they had been improving perfomance, but it is not perfect yet, which seems to be exact your case, 48-52fps is not perfect, but is not so bad too.

**Comment by DAN-AND-DNA** [comment]
@erickzanardo thanks
