### ISSUE TITLE
Performance testing

### ISSUE THREAD

**Issue by Tokenyet** [flame-engine/flame#330]
Hi, is there any benchmark about the flame performance testing? I just create a simple example for flame, but got 30fps in Xiaomi 5s plus. (500 objects)

```dart
import 'dart:ui';
import 'package:flame/game.dart';
import 'package:flame/position.dart';
import 'package:flame/text_config.dart';

import 'package:flutter/material.dart';

class EmptyGame extends BaseGame {
  final TextConfig fpsTextConfig =
    const TextConfig(color: Color(0xFFFFFFFF));

  static final Paint paint = Paint()..color = const Color(0xFF888888);

  @override
  void resize(Size size) {
    super.resize(size);
  }

  @override
  void onDetach() {
    super.onDetach();
  }

  @override
  Color backgroundColor() => Color(0xff2e2e2e);

  void _start() {
  }

  @override
  void update(double dt) {
  }

  @override
  void render(Canvas canvas) {
    int count = 500;
    double windowH = window.physicalSize.height;
    double windowW = window.physicalSize.width;
    double singleW = windowW / count;
    double singleH = windowH / count;
    for(int i = 0; i < count; i++) {
      canvas.save();
      canvas.saveLayer(null, Paint());
      canvas.drawCircle(
        Offset(i * singleW, i * singleH),
        singleW * 0.5,
        Paint()
      );
      canvas.restore();
      canvas.restore();
    }
    trackFps(canvas);
  }

  DateTime lastTime;
  int lastFps = 0;
  int incrementalfps = 0;
  void trackFps(Canvas canvas)
  {
    if(lastTime == null) lastTime = DateTime.now();
    incrementalfps++;
    if(DateTime.now().difference(lastTime).inMilliseconds > 1000) {
      lastTime = DateTime.now();
      lastFps = incrementalfps;
      incrementalfps = 0;
    }

    fpsTextConfig.render(canvas, lastFps.toString(), Position(0, 10));
  }
}
```

Enviroment:
```
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.18362.778], locale zh-TW)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.44.1)
[√] Connected device (1 available)
```

Just wondering, Is this normal for flame? and how many fps do you use this example. 

By the way, in `release` mode, It's about 42 fps, still have a bit far from 60 fps. According to the test, I think there is really less cpu resource or complex rendering we could use, because we should at least keep the game on 30fps, and 42-30=12fps means the remaining computation should only limit in 9.5ms. I think It's the limitation of flutter, unless flutter support [instancing](https://learnopengl.com/Advanced-OpenGL/Instancing) or low level api.

**Comment by erickzanardo** [comment]
I just made a small perfomance test, you can check it here: https://github.com/flame-engine/flame_perfomance_test_game

I am not sure why your example lead to those results. But as you can see on the example I sent it tops 60fps almost all the times, there are some spikes of low fps sometimes, but it is probably because of the non-performant collision detection method I used for this example.

This test was ran on release mode, on a Moto Z2 Play, running Android 9.

**Comment by erickzanardo** [comment]
Also, you could probably optimize your example by not doing the following calculation on ever render:

```
    int count = 500;
    double windowH = window.physicalSize.height;
    double windowW = window.physicalSize.width;
    double singleW = windowW / count;
    double singleH = windowH / count;
```

**Comment by Tokenyet** [comment]
I think my example is an minimal example to test flutter's ability, Just want to share the profile I got in debug mode (Because cpu profile only available in debug mode).

![image](https://user-images.githubusercontent.com/6420527/82112556-6e475c80-9780-11ea-9cea-150e031f7e36.png)

By the way, I used the example [flame_perfomance_test_game](https://github.com/flame-engine/flame_perfomance_test_game), It's unstable in the range 30~60 when objects are > 500 with `trackFps` that I provided in the example, since I can't use `fps(120).toString()`, that always return 0, so I used my method.

**Comment by erickzanardo** [comment]
@Tokenyet thanks for sharing this profile.

Indeed to use the `fps(120).toString()` you need a modified version of Flame to do that, I have already submitted a PR for, but it is still in discussion, but you can check it here https://github.com/flame-engine/flame/pull/337

Using Flame from that branch, you will be able to use the `fps` method.

**Comment by luanpotter** [comment]
Other things to optimize in your example:

1. you call canvas.saveLayer 500 times every frame, not sure why that is needed, if you use the component system that won't happen.
2. creating lots of instances on each component on render: if you used the component system, you wouldn't need to recreate a lot of instances for every component x every frame.
3. optimize objects: since your object don't move or change, you can render then to a image and then render that image very frame, and update the image if your grid ever changes. we do that for tile maps, game boards, backgrounds, anything that is static (like your example).
