### ISSUE TITLE
Flame.audio performance issues

### ISSUE THREAD

**Issue by JamesMudge** [flame-engine/flame#34]
Calls to Flame.audio.play() have a high performance impact.

I lose 5-15 frames making as few as two calls per second on a physical android s5.

**Comment by luanpotter** [comment]
Hi, @JamesMudge , thanks for your feedback! If you are playing audios on that high frequency, you probably should consider using an AudioPool, instead of Flame.audio. Creating and buffering audioplayers instances is indeed very, very expensive. There is nothing you can do, other than preload everything before you use it. Could you please test that and see if the results are better?

**Comment by JamesMudge** [comment]
I should have noted that I am using Flame.audio.loadAll([...]) to pre cache all the sounds well before I try to use them.
