### ISSUE TITLE
Sprite transforms

### ISSUE THREAD

**Issue by Jayx239** [flame-engine/flame#378]
I am currently working on a game and the sprite sheet I am using has odd layouts for some of the sprites. For example, the sprite sheet has images that go in order from left to right as well as others that go top to bottom and some that are angled diagonally. For this particular sheet, the sprites are essentially the same images, just rotated. I would find it useful to have the ability to do the followoing:

I would like to be able to load the sprite going left to right, but when rendering it, rotated each of the sprite blocks at an angle. For example, if the sprite depicts a character image walking down, I would like the sprite animation to rotate the image 90 degrees when rendering so the animation looks like the the character is walking to the right.

Is this a feature that flame currently supports?

Is this something that others would find beneficial? If so I could find time to make the change and open a pull request.

**Comment by erickzanardo** [comment]
I am not sure if I understood correctly. But if you want rotate, flip and etc a Sprite, `SpriteComponent` already supports a lot of those transformations. And even if not using Components, most of transformations are available on the Canvas.

Could explain better what is your need?

**Comment by illiapoplawski** [comment]
I'm also interested in a similar feature (I believe it's the same as what @Jayx239 is proposing so let me know if I'm asking the same thing @Jayx239 ).  Currently, spritesheet in flame only handles identically sized sprites and they are stored 2D grid using their x,y index times their width to determine their position in the sprite sheet.  However, some sprite sheets (like in my situation) have different sized sprites or sprites that are rotated.  Because of this, a sprite needs to know its x, y position, its width and height, as well as whether or not it is rotated on the spritesheet.  You could then either access the sprite based on its starting x,y position or you can have Map <String, Sprite> where each sprite is uniquely named and can then be accessed using its name rather than its x,y index in the table.  Here's a link of a spritesheet [online](https://phaser.io/content/tutorials/advanced-rendering-tutorial/tp-rotated.png) which shows what I mean for more complex sprite sheets.

**Comment by erickzanardo** [comment]
> I'm also interested in a similar feature (I believe it's the same as what @Jayx239 is proposing so let me know if I'm asking the same thing @Jayx239 ).  Currently, spritesheet in flame only handles identically sized sprites and they are stored 2D grid using their x,y index times their width to determine their position in the sprite sheet.  However, some sprite sheets (like in my situation) have different sized sprites or sprites that are rotated.  Because of this, a sprite needs to know its x, y position, its width and height, as well as whether or not it is rotated on the spritesheet.  You could then either access the sprite based on its starting x,y position or you can have Map <String, Sprite> where each sprite is uniquely named and can then be accessed using its name rather than its x,y index in the table.  Here's a link of a spritesheet [online](https://phaser.io/content/tutorials/advanced-rendering-tutorial/tp-rotated.png) which shows what I mean for more complex sprite sheets.

If I understood correctly, most of what you need is provided by the fire atlas tool that we provide for Flame. The only thing missing, which would be a nice addition, is the angle.

Please take a look on our GitHub organization for the fire atlas project, it should pretty straight forward to understand how to use it, I am away from a computer now and can’t elaborate much right now, but I sure can explain more tomorrow if needed.

**Comment by illiapoplawski** [comment]
It will definitely be promising after it supports rotation.  In my case I won't be able to use it normally as I am making a puzzle app that gives the user full control over how the pieces are created and shaped.  To optimize the app better, I have ported over this [project](https://github.com/TeamHypersomnia/rectpack2D) to dart to parse through all the puzzle pieces automatically and generate a spritesheet and the corresponding json which will allow me to only load one image rather than ~1000 sprites when loading the puzzle.  I could however potentially tie into fire atlas to have it create the json from my rects in code rather than using the online editor and then use the .fa file in the flame app.  Otherwise I may just create spritecomponents and since I know the rotation from my json file initialize them with that rotation on creation.  I'm going on holidays for the week though so I will look into it once I get back.

**Comment by erickzanardo** [comment]
Very interesting @illiapoplawski , so If indeed this issue is about what fire atlas is meant to do, I am going to close this issue and ask the the author, or even you @illiapoplawski if you are up to, to open improvements issues on the fire atlas repository, so we can track this on the correct repository.
