### ISSUE TITLE
How to set collision detection for flare animation?

### ISSUE THREAD

**Issue by LBXjixiangniao** [flame-engine/flame#443]

**Comment by erickzanardo** [comment]
@renancaraujo can you help us here?

**Comment by renancaraujo** [comment]
Yeah, at first we can since `FlareActorComponent` is a `PositionComponent` and therefore we have as rect shaped area that can be used for the collision. 

But if the case is to define a collision area based on a flare **shape**, you may need to retrieve it somehow via flares API (maybe via `getNode`).

**Comment by LBXjixiangniao** [comment]
@renancaraujo It seems that the flares API cannot get the actual size of the content during the animation. For example, when a person is animated, is there a way to get the height of the person after squatting?

**Comment by renancaraujo** [comment]
Via the getNode api you can get (and update) the position of specific nodes in the animation (like in the [teddy example)](https://github.com/2d-inc/Flare-Flutter/tree/master/example/teddy). It could be possible if there enough nodes in the flare animation.

**Comment by erickzanardo** [comment]
Please let us know if the advice provided didn't solved your question. For the future, open issue about flare on its own repository here: https://github.com/flame-engine/flame_flare
