### ISSUE TITLE
Smooth camera follow

### ISSUE THREAD

**Issue by glennmichaelmejias** [flame-engine/flame#447]
Is it possible to make a smooth camera follow?

**Comment by erickzanardo** [comment]
This may help you https://fireslime.xyz/articles/20190911_Basic_Camera_Usage_In_Flame.html

**Comment by Dannark** [comment]
Its pretty ease, Just use `lerp `interpolation maths. 

```
import 'dart:ui' as ui;

...
var cameraSpeed = 1; //controls how much smoothness you want
var posX = 0;
var posY = 0;

update(){
    posX = ui.lerpDouble(posX, targetPos.dx, GameController.deltaTime * cameraSpeed);
    posY = ui.lerpDouble(posY, targetPos.dy, GameController.deltaTime * cameraSpeed);
}
```

In this way you will move an object to one point to another, the deltaTime is the time passed since the lastframe, it is necesseary if you want this to run equallys in 30, 60 or any other fps, since it uses the time to make this interpolation, and not just the how many iterations loops it passed.

Ah but to move only the camera and let the all others objects offsets accorently, you still have to implement a logic to save the canvas state before moving 

[![lerp camera](https://user-images.githubusercontent.com/7622553/90346169-2cd38100-dffd-11ea-8af3-212d453a0e49.gif)](https://github.com/Dannark/bwo)

```
c.save();
    c.translate(posX - borderSize, posY - borderSize);
...
//move elements on canvas like trees etc

c.restore();//call it after all objects on the map was drawn
```

I did it on my project if you want an example:
[borderless world online](https://github.com/Dannark/BWO/blob/master/lib/Map/map_controller.dart)

**Comment by glennmichaelmejias** [comment]
@Dannark have you tried using the box2d camera follow? i can only update the camera on update and i cannot update it on button click perhaps.

**Comment by Dannark** [comment]
@glennmichaelmejias No, I didn't try that, can you show me your code?

Another thing, Does this button fires only once when it's clicked?

**Comment by Dannark** [comment]
Check it out, here is a full example:
[Smooth Camera Follow](https://github.com/Dannark/FlameExamples/blob/master/lib/examples/smooth_camera_follow/smooth_camera_follow.dart)

**Comment by erickzanardo** [comment]
Let us know if the advice received here didn't solved your question, closing this for now.
