### ISSUE TITLE
Strange behavior when trying to use onTapDown from Tapable and setting an angle other than zero

### ISSUE THREAD

**Issue by Bes79** [flame-engine/flame#449]
class LeafComponent extends SpeedComponent {
  LeafComponent() : super('Leaf.flr', 'Show', 50, 50){
    angle = math.pi * 2 * leafRand.nextDouble();
  }

  @override
  void onTapDown(TapDownDetails details) {
    // TODO: implement onTapDown

    controller.Start([SpeedAnimation('Hide')]);
    super.onTapDown(details);
  }
}

when i change angle property and try to click on area 1 component dont see that, but if i click on area 2 it is ok.

![image](https://user-images.githubusercontent.com/29800408/90817897-e6e92680-e336-11ea-86de-2769cb349388.png)

**Comment by luanpotter** [comment]
The current tappable implementation doesn't consider the angle for bounding box detection. In fact, toRect never considers the angle because it returns an AA (axis-aligned) rectangle. My idea for fixing this is counter-rotating the point with respect to the anchor point and check collision on that space.

I normally use anchor center in which case this problem is barely noticeable if width ~= height.

**Comment by spydon** [comment]
This will be solved in v1.0.0-rc3
(Solved in PR #548)
