### ISSUE TITLE
Is it possible to render a component outside of game.render().

### ISSUE THREAD

**Issue by cloudseasail** [flame-engine/flame#487]
I like to show a sprite on canvas when user Tapdown,  however I noticed "small lag" between Tapdown and sprite show.
I think this is because the game.render() not run directly after component created (in the Tapdown event).
So wondering if there is any way to render directly in Tapdown event,  instead of waiting for next render tick?

This is not FPS issue,  I record my FPS which is 60 perfectly. I also run the flame gesture exmaple and I noticed similiar "lag".
I understand this lag is small,  however it is not a good expeirence in the game that user would has bad feeling that game is lagging.

**Comment by luanpotter** [comment]
It doesn't make sense to render outside of render. If the game is running at 60 FPS, render will be called at most (worst case) 17ms after the handler. that is faster than humans can perceive. The whole idea of the game loop is to render as fast as possible, otherwise the whole game will look like it's moving in steps.

What I think you are seeing is a delay in the handler of on clicks by your device/flutter. try adding a log line when the tap handler is called and try to see the delay is already there. Nothing that can be done on that regard, AFAIK. Of course using the right detector help: tap up only triggers after a while, if you have a double tap detector, the single tap will take longer to register. tap down should be the fastest. For more details check the flutter page about input: https://flutter.dev/docs/development/ui/advanced/gestures

I'm closing this for now but feel free to open other issues as needed, but please abide by the issue template next time.

**Comment by spydon** [comment]
Could it be the async loading of the sprite that @cloudseasail is experiencing?
