### ISSUE TITLE
[1.0.0] Should we clone position on the PositionComponent setter?

### ISSUE THREAD

**Issue by luanpotter** [flame-engine/flame#503]
So currently if you do:

```dart
  component.position = position
```

For a Position component it does *not* create a clone. I just wanted to discuss if this is our desired behaviour. These are the side effects:

### No clone

If you do
```dart
  crate.position = car.position
```

They will be linked forever. Which might be intended or not, or might be a bit confusing.

### Cloning

If you do

```dart
  final p = Vector2.all(10)
  crate.position = p
  p.x = 100
```

It won't move the box. Which might be intended or not, or might be a bit confusing.

---

Either way I don't think it's a bit clear, it just crossed my mind while I ported the old flame_crates_example and I wanted to flag. Regardless of the choice it's abundantly clear what will happen just looking at the code (which is what I did).

**Comment by spydon** [comment]
I wrote up a PR for it so that it sets the values to position instead of changing the reference, but I think it might be more confusing. 
Because then we should also do the same on `size` and then I thought there are probably cases where you want to control the sizes of many components at the same time by just changing the same `Vector2`. And then I thought maybe the same is true for `position`, for example if you have several sprites on top of each other?

My suggestion is that we keep it like it is now and let the user handle cloning of the vector2, or to use `position.setFrom(v)`.

**Comment by erickzanardo** [comment]
is this discussion still valid after all the changes we did?

**Comment by spydon** [comment]
It is, we still don't have a setter which does `clone` on the argument to `position` on `PositionComponent`, we just have to decide whether that is something we want or not. If we do add it the user doesn't accidentally tie that Vector2 to something else, but it also restricts the user from controlling the position of multiple components at the same time through one single `Vector2`.

**Comment by erickzanardo** [comment]
I see, IMO we shouldn't clone, so we create less instances, and hopefully get a better performance?

**Comment by spydon** [comment]
Let's keep it as is then, I don't think @luanpotter had any strong opinions on the matter either.
(Otherwise we can just re-open it)

**Comment by erickzanardo** [comment]
SGTM
