### ISSUE TITLE
IsometricTileMap render method

### ISSUE THREAD

**Issue by Alex-A4** [flame-engine/flame#626]
Hey there!
Just learning Flame and watch for IsometricTileMaps, I really can't understand why the render method line looks like this:

`final p = getBlockPositionInts(j, i);`

Isn't it should be:

`final p = getBlockPositionInts(i, j);`

Flame version:
`flame: ^1.0.0-rc5`

Whole render method:
```
void render(Canvas c) {
    super.render(c);

    final size = effectiveTileSize;
    for (int i = 0; i < matrix.length; i++) {
      for (int j = 0; j < matrix[i].length; j++) {
        final element = matrix[i][j];
        if (element != -1) {
          final sprite = tileset.getSpriteById(element);
          final p = getBlockPositionInts(j, i);
          sprite.render(c, position: p, size: size);
        }
      }
    }
  }
```

Looks like it's inverting rows and columns. Is that a bug or feature?

The problem is that in the [example](https://github.com/flame-engine/flame/tree/master/doc/examples/isometric) it draws empty block on correct matrix value, and vice versa.

**Comment by luanpotter** [comment]
what are rows and columns? that is just a matter of definition right? is there any standard I am missing? I just did the way it made sense in my head

**Comment by luanpotter** [comment]
(I am ok with replacing i<=>j btw if that makes more sense, just trying to understand the rationale)

**Comment by Alex-A4** [comment]
When it's j,i it rotates the result matrix and looks strange

**Comment by Alex-A4** [comment]
In the example empty square should not be clicked but it is. Because matrix rotated 90 degree to right

**Comment by luanpotter** [comment]
I'm so sorry but I'm really not sure I see what you are saying... We are transforming a matrix (which has no inherent geometrical representation but can be seen as a 2d cartesian space by the way we write it in the code) to a representation in isometric space. There is no unique way of transforming the x and y axis from 2d cartesian to isometric; there might be one standard way, which, I believe, is the one I used (because I read an article about the math of coordinate transformations to get the code and used that).

Here are the images for better illustration, of the matrix as seen "drawn" in the src code (in this case you can imagine that it has (horizontal) rows and (vertical) columns):

![image](https://user-images.githubusercontent.com/882703/107466713-86db7c00-6b32-11eb-81e8-bdf91f46c796.png)

And here how it's rendered. Note that there is no horizontal and vertical axis in isometric coordinates, it uses a different coordinate system.

![image](https://user-images.githubusercontent.com/882703/107466776-a4a8e100-6b32-11eb-99de-8412c1aea63a.png)

As you can see I even paint the origin of the isometric coordinate system in magenta in the example precisely to make sure it was clear what transformation was going on.

I'm ok with changing this but I would ask for at least some reference that establishes a contradicting standard. Again, it's all a matter of definition but I am willing to follow the existing defaults (I'm not super familiar with isometric coordinate transformations literature).

cc @renancaraujo @erickzanardo @spydon @wolfenrain if you have thoughts on this

**Comment by spydon** [comment]
I don't think it really matters here, but if it makes users confused maybe it would be a good idea to swap them (even though it doesn't make a difference)?

**Comment by erickzanardo** [comment]
> I'm ok with changing this but I would ask for at least some reference that establishes a contradicting standard.
I agree with that, It don't seem to matter much, but if there is a standard our there, that we are missing, I vote to change, otherwise I think we should maintain the current implementation.

**Comment by luanpotter** [comment]
AFAIK the most standard we have is the one I used.

@spydon the opposite could be equally confusing right?

**Comment by wolfenrain** [comment]
I agree with @luanpotter / @erickzanardo  on this, unless there is a standard that we should uphold, I vote to not change it.

**Comment by spydon** [comment]
Let's close this one then, and if someone comes up with a standardized way that is different from the one we are using right now we can re-open it.
