### ISSUE TITLE
approach for changes "rooms" (screens) for a Flame 2D app? 

### ISSUE THREAD

**Issue by callagga** [flame-engine/flame#645]
Question - What approach would one use in a Flame 2D simple RPG app, which is just different rooms that can you navigate between?  Is there something within Flame I should be looked at & what would the persistance mechanism you would recommend (e.g. which state the the user was in before quitting the game).    

Would this best be done within Flame as opposed to using Flutter screens/routes to track the progression of the user through "rooms" and then jump into each room after this?

**Comment by erickzanardo** [comment]
There are many ways of achieving that, Flame don't bundle any specific APIs for rooms of something like that, but if I were to implement something like that, I would probably create Components to represent the rooms and add the game objects, player, enemies and etc as its children. So when changing rooms, I could just remove that component and add the other one.

Regarding persistence, there are multiple packages for that, if you will be saving simple data, `shared_preferences` is a good choice. Otherwise `hive` would be a nice choice for complex data.

If you have more questions like that, please consider joining our discord, we a bunch of good people there that could discuss and give more ideas, Github Issues are meant for tracking and report of bugs and problems. Closing this since this isn't an issue.

**Comment by callagga** [comment]
ok - many thanks
