### ISSUE TITLE
Components don't compose properly without HasGameRef

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#900]
Here I'm creating a simple component, and then adding another component to the first:
```
class AComponent extends BaseComponent {}

void main() {
  group('game ref tests', () {
    test('nested components without gameRef', () {
      final game = MyGame() .. onResize(Vector2.zero());
      final a = AComponent();
      game.add(a);
      game.update(0);
      final aa = AComponent();
      a.addChild(aa);
      game.update(0);
    });
  });
}
```
However, this produces the following error:
```
Testing started at 6:47 PM ...
/Users/pasha/flutter/bin/flutter --no-color test --machine --start-paused --plain-name "nested components without gameRef" test/components/has_game_ref_test.dart

dart:core                                                _AssertionError._throwNew
package:flame/src/components/base_component.dart 155:9   BaseComponent.prepare
package:flame/src/components/component_set.dart 75:12    ComponentSet.addChild
package:flame/src/components/base_component.dart 176:21  BaseComponent.addChild
test/components/has_game_ref_test.dart 42:9              main.<fn>.<fn>
===== asynchronous gap ===========================
dart:async                                               _completeOnAsyncError
package:flame/src/components/component_set.dart          ComponentSet.addChild
package:flame/src/components/base_component.dart 176:21  BaseComponent.addChild
test/components/has_game_ref_test.dart 42:9              main.<fn>.<fn>

'package:flame/src/components/base_component.dart': Failed assertion: line 155 pos 9: '!isMounted': Parent was already added to Game and has no HasGameRef; in this case, gameRef is mandatory.
```

I  believe this is a bug since mixins shouldn't be mandatory.

**Comment by st-pasha** [comment]
I couldn't find any clear documentation on when in the component's lifecycle the `gameRef` is guaranteed to become available.

For example, if it is ok for the mixin to work starting from the `onMount()` event, then I can fix this bug easily. On the other hand, if you want `gameRef` to be accessible in `onLoad()`, then it will be more complicated.

**Comment by spydon** [comment]
Yeah, `gameRef` has to be accessible from `onLoad` since it can be used to load sprites etc.

Right now you have to either add the children to the parent component before it is being added to the game, or your parent has to have the `HasGameRef` mixin. This is due to that the `gameRef` is used to prepare the component. This could potentially be solved by the restructuring of things so that `Game` is just a component, because then the parent could be responsible for preparing its children instead of the `Game`. If you have any other ideas we are all ears.

**Comment by st-pasha** [comment]
As far as I understand, the problem occurs if we first create a component `A`, then create `B` and add it as `A`'s child, and then finally add `A` to the `Game`. The problem then is that during `A.addChild(B)` we call `B.onLoad()`, but at that point `A` is still detached from the game, so there is no way for it to know the game-ref.

A possible solution then is to check in `A.addChild()` whether `A` is (weakly) mounted or not. If `A` is weakly mounted, then all is good and we can call `B.onLoad()` as we already do. However, if `A` is not mounted, then we skip loading `B`. Instead, when `A` gets finally added to the game tree, it would iterate over its children and call `onLoad()` then. 

Note that I distinguish here between being "strongly" mounted (a component has run `onLoad`, `onMount`, it has a parent which is also strongly mounted, and it has been added to parent's `components` list), and "weakly" mounted (a component has a parent and it is possible to reach the root by following the parents, but otherwise it may not have run `onLoad` or `onMount`, and it may not have been added to parent's `components` list).

The only drawback that I see with this plan is that when we create `A->B` subtree, currently `B` would begin loading right away, whereas with the proposed changes `B` will begin to load only when `A` is added to the game tree. I don't see this as such a big issue, since currently a standalone component `A` will not begin loading until you add it into the tree, so there is no reason to demand that `B` in `A->B` should have a more eager behavior.

Sorry if this explanation is a bit confusing.

**Comment by spydon** [comment]
This only happens if `B` is `HasGameRef` right? You could just add the `gameRef` in the `addChild` call?
I think that it isn't necessarily a drawback that the child loads when the parent is added in your proposal.
If you want to work on this I think it could make sense, but I think the optional argument to `addChild` should cover most situations already. Let's see what the others in the team says too. @flame-engine/flame-colab

**Comment by st-pasha** [comment]
I'm worried about the situations where you would need to provide `gameRef:` in `addChild` call, but there is no way to do so.

For example, imagine that `A` is **not** `HasGameRef`, and it wants to add `B` which is `HasGameRef`. How would `A` be able to call the `addChild(B(), gameRef:???)` then? 

Or maybe neither `A` nor `B` are `HasGameRef`, but now you want to change `B` to give it a game-ref -- is this gonna break your code because you would need to update all cases where `B` is instantiated and added to a parent?

**Comment by spydon** [comment]
Like I said, I think it could make sense to traverse the child tree when adding a component to add `gameRef`s where needed.

1. But you are in full control of the A code right? So you can just add `HasGameRef` where needed.

2. How would you be able to dynamically give B a `gameRef`, or you mean not through the mixin? Would the proposed solution really help with that?

**Comment by st-pasha** [comment]
I guess my comments describe more of a nuisance than an insurmountable problem. 

In case 1, you could have a deep tree `A -> B -> C -> D`, where only the last component needs `HasGameRef`,  but now it forces all the other components up the hierarchy to also have the same mixin. And what if `D` is used in multiple places?

In case 2, I was imagining a situation where `B` originally doesn't have a `gameRef`, and it was developed as such, and already used in the game in many places. Now, a new requirement comes in, and you need to change `B` to have a `HasGameRef`. This would then require updating not only `B`'s code, but also potentially all places where `B` is added into the game. This could be problematic, as it would create errors that appear only during runtime. So if, for example, you forgot to update one of the possibly obscure places where `B` is instantiated, then it can produce an error only much later on (possibly even in production, if the tests are not thorough enough).

Also, I think you mentioned in some other PR that you want to have nested games. Not sure how this will be implemented, but I can see a potential problem if `A` is `HasGameRef<T>` while `B` wants to be `HasGameRef<S>` -- since A can't carry two different game refs (or can it?).

**Comment by spydon** [comment]
Like I said earlier I think it makes sense to handle this.

Case 1: The last part can't happen since a component can only have one parent and I agree the first part would be problematic.

Case 2: If B is added directly to a game then you wouldn't have to update anything, but I guess you mean if it is added as a child to a non-`HasGameRef` component?

> Also, I think you mentioned in some other PR that you want to have nested games. Not sure how this will be implemented, but I can see a potential problem if A is HasGameRef<T> while B wants to be HasGameRef<-> -- since A can't carry two different game refs (or can it?).

I'm not sure if this is something that is possible for us to handle from the engine side, if the user wants to move a component from one game type to another that that component doesn't support that shouldn't be allowed. The user will have to make a common game class that their games can extend and pass that in as the type if they want to support multiple games of a more specific type than `BaseGame`.
